"""Call ACTIVITY — volume and answerability. **Read only.**

Ported from BonviZvonki ``modules/analytics/application/activity.py``
(``ActivityService``). Every query, every join and every reason for them is
theirs; what changed is named at each seam below. The terms this report uses —
and why "unanswered" is never one number — are in ``rules.py``.

This module owns no table and is declared in ``core/reads.py``
(CONVENTIONS.md §2.1), so three rules bind it and ``tests/test_layering.py``
checks all three: it reads only ``calls.CallModel`` and ``agents.AgentModel``,
it never writes, and it never selects a bare ORM entity — only projections and
aggregates, so nothing foreign can escape past this boundary.

════════════════════════════════════════════════════════════════
 THE SEAMS THAT CHANGED, AND WHY
════════════════════════════════════════════════════════════════

**The phone key is a column, not an expression.** BonviZvonki matches
customers with
``right(regexp_replace(coalesce(calls.client_phone,''),'\\D','','g'), 9)``
written as a ``literal_column`` — with a long comment about bind parameters:
``func.coalesce(column, "")`` turns the empty string into ``$1``, the same
expression in SELECT and in GROUP BY then gets two different parameter
numbers, PostgreSQL calls them different expressions and raises
"client_phone must appear in the GROUP BY clause". BonviCall has
``calls.remote_number_key``, a STORED generated column produced by
``core.phone.phone_key_sql`` and indexed by ``ix_calls_remote``, so the whole
problem and its workaround disappear. ``length(tail) = 9`` becomes
``remote_number_key IS NOT NULL``, which is the same test: the generated
column is NULL for anything shorter, deliberately (N37 — a 4-digit extension
used as a key matches the tail of every long number).

**Answered/unanswered is a NOT NULL enum here**, so the ``unknown`` family and
the ``inbound_known`` denominator are gone. ``rules.py`` says why in full.

**The window is whole Asia/Tashkent days**, resolved once in
``rules.activity_window`` and passed in, so this module never touches a clock.

**Own-scope narrowing is this module's job.** A ``sales`` principal holds
``calls:read:own`` and the query is narrowed to their own agent, exactly as
``CallService._scoped`` does it — the permission decides, the query narrows,
and there is never a second check (CONVENTIONS.md §11).
"""

from __future__ import annotations

import uuid
from datetime import timedelta

from sqlalchemy import Integer, and_, case, func, literal_column, or_, select, text
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import aliased

from src.core.clock import TASHKENT
from src.core.deps import Principal
from src.core.enums import CallDirection, CallDisposition
from src.core.permissions import Perm
from src.modules.activity.rules import (
    CALLBACK_WINDOW_HOURS,
    WORK_HOURS,
    ActivityDay,
    ActivityHour,
    ActivityReport,
    AgentActivity,
    MissedClient,
    Window,
    day_span,
    sum_rows,
)
from src.modules.agents.models import AgentModel
from src.modules.calls.models import CallModel

#: Permissions that see the whole fleet. Anything else is narrowed to the
#: principal's own agent — the shape ``CallService._scoped`` already uses.
#: Exactly the fleet-wide half of the router's gate: the gate admits
#: ``calls:read`` and ``calls:read:own``, so ``calls:read`` is the only
#: permission that widens the query, and listing more would be a second,
#: drifting definition of "may see everybody".
FLEET_WIDE: tuple[str, ...] = (Perm.CALLS_READ,)

_OUTGOING = CallModel.direction == CallDirection.OUTGOING
_INCOMING = CallModel.direction == CallDirection.INCOMING
_ANSWERED = CallModel.disposition == CallDisposition.ANSWERED
_NO_ANSWER = CallModel.disposition == CallDisposition.NO_ANSWER

#: INCOMING and no conversation: ``missed`` or ``rejected``. See
#: ``rules.AgentActivity.missed`` for why ``rejected`` belongs here.
_MISSED = and_(_INCOMING, CallModel.disposition != CallDisposition.ANSWERED)

#: The matching key, indexed and generated by the database (N37).
_TAIL = CallModel.remote_number_key


def _count(*conditions) -> object:
    """``COUNT`` of the rows matching every condition. NULL rows count zero."""
    return func.count(case((and_(*conditions), 1)))


class CallbackStats:
    """Per-agent callback aggregates, keyed by agent id."""

    __slots__ = (
        "addressable",
        "clients",
        "events_closed",
        "median_minutes",
        "medians",
        "reached",
    )

    def __init__(
        self,
        clients: dict[uuid.UUID, int],
        reached: dict[uuid.UUID, int],
        events_closed: dict[uuid.UUID, int],
        addressable: dict[uuid.UUID, int],
        medians: dict[uuid.UUID, float],
        median_minutes: float | None,
    ) -> None:
        self.clients = clients
        """Customers who could not get through."""
        self.reached = reached
        """Of those, the ones contacted afterwards."""
        self.events_closed = events_closed
        """Missed EVENTS considered closed."""
        self.addressable = addressable
        """Missed events carrying a usable number."""
        self.medians = medians
        """Each agent's median minutes to contact."""
        self.median_minutes = median_minutes
        """The window's own median — never the median of medians."""


class ActivityService:
    """Activity figures. Reads only (CONVENTIONS.md §2.1)."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    # ── Scope ─────────────────────────────────────────────────

    def _scope(
        self, principal: Principal, agent_id: list[uuid.UUID] | None
    ) -> list[uuid.UUID] | None:
        """The agents this caller may see, narrowed by permission.

        ⚠️ A ``sales`` principal's ``agent_id`` filter from the URL is
        IGNORED, not merged: a salesperson must not be able to name a
        colleague and read their activity. They see exactly one agent — their
        own — and a ``sales`` account with no linked agent sees nothing rather
        than everything (the database CHECK makes that state unreachable; this
        is the belt to its braces).

        ``None`` means "every agent", which is only ever returned for a
        fleet-wide principal.
        """
        if not principal.has_any(*FLEET_WIDE):
            return [principal.agent_id] if principal.agent_id else []
        return list(agent_id) if agent_id else None

    def may_read_agent(self, principal: Principal, agent_id: uuid.UUID) -> bool:
        """Whether this caller may read one named agent's detail.

        A caller who may not is answered **404**, never 403: a 403 would
        confirm that this agent exists and spoke to that number
        (``core/permissions.py``, SPEC §4.1 rule 2). BonviZvonki raises
        ``ForbiddenError`` here, which leaks exactly that.
        """
        allowed = self._scope(principal, None)
        return allowed is None or agent_id in allowed

    # ── The report ────────────────────────────────────────────

    async def report(
        self,
        principal: Principal,
        window: Window,
        agent_id: list[uuid.UUID] | None = None,
    ) -> ActivityReport:
        """Who called whom, how many went unanswered, and who was called back."""
        agents = self._scope(principal, agent_id)
        report = ActivityReport(window=window)
        rows = await self._per_agent(window, agents)
        report.agents = rows

        callbacks = await self._callbacks(window, agents)
        for row in rows:
            row.missed_clients = callbacks.clients.get(row.agent_id, 0)
            row.clients_reached = callbacks.reached.get(row.agent_id, 0)
            row.missed_called_back = callbacks.events_closed.get(row.agent_id, 0)
            row.missed_addressable = callbacks.addressable.get(row.agent_id, 0)
            row.callback_median_minutes = callbacks.medians.get(row.agent_id)

        total = sum_rows(rows)

        # ⚠️ THE CUSTOMER COUNTS ARE NOT SUMMED FROM THE ROWS. One customer
        # can call two employees: per employee that is correctly two rows,
        # company-wide it is one person. Summing inflates the headline —
        # measured at BonviZvonki, 151 instead of 145 over two days. The
        # number a manager reads is this one, so it gets its own
        # de-duplicated query.
        company = await self._callbacks(window, agents, per_agent=False)
        total.missed_clients = sum(company.clients.values())
        total.clients_reached = sum(company.reached.values())
        report.total = total

        # ⚠️ THE MEDIAN IS THE COMPANY'S TOO, not an average of the agents'.
        # Per agent, a customer who called two employees is counted twice and
        # shifts the median. The card puts the callback RATE (per customer)
        # and the median side by side; computed over different units they
        # would contradict each other — measured, 5.1 minutes per agent
        # against 4.1 per customer for the same day.
        report.callback_median_minutes = company.median_minutes
        report.days_series = await self._days(window, agents)
        report.hours_series = await self._hours(window, agents)
        return report

    # ── Per agent ─────────────────────────────────────────────

    async def _per_agent(
        self, window: Window, agents: list[uuid.UUID] | None
    ) -> list[AgentActivity]:
        statement = (
            select(
                AgentModel.id,
                AgentModel.full_name,
                _count(_OUTGOING).label("outbound_total"),
                _count(_OUTGOING, _ANSWERED).label("outbound_answered"),
                _count(_OUTGOING, _NO_ANSWER).label("outbound_no_answer"),
                _count(_INCOMING).label("inbound_total"),
                _count(_INCOMING, _ANSWERED).label("inbound_answered"),
                _count(_MISSED).label("missed"),
                func.coalesce(func.sum(CallModel.duration_sec), 0).label("talk"),
            )
            .select_from(AgentModel)
            # LEFT JOIN — an employee who made no call at all in the window
            # must still appear. An inner join hides them, and "this person
            # did nothing" may be the most important finding in the report.
            .outerjoin(
                CallModel,
                and_(
                    CallModel.agent_id == AgentModel.id,
                    CallModel.started_at >= window.since,
                    CallModel.started_at < window.until,
                ),
            )
            .where(AgentModel.archived_at.is_(None))
            .group_by(AgentModel.id, AgentModel.full_name)
            .order_by(func.count(CallModel.id).desc(), AgentModel.full_name)
        )
        if agents is not None:
            statement = statement.where(AgentModel.id.in_(agents))

        return [
            AgentActivity(
                agent_id=row.id,
                agent_name=row.full_name,
                outbound_total=int(row.outbound_total or 0),
                outbound_answered=int(row.outbound_answered or 0),
                outbound_no_answer=int(row.outbound_no_answer or 0),
                inbound_total=int(row.inbound_total or 0),
                inbound_answered=int(row.inbound_answered or 0),
                missed=int(row.missed or 0),
                talk_seconds=int(row.talk or 0),
            )
            for row in await self.session.execute(statement)
        ]

    # ── Daily volume ──────────────────────────────────────────

    async def _days(
        self, window: Window, agents: list[uuid.UUID] | None
    ) -> list[ActivityDay]:
        """Volume per local day. Empty days come back too (``rules.day_span``).

        ⚠️ Bucketed in LOCAL time. In UTC the day boundary falls at 05:00
        Tashkent and calls after midnight land on the previous day, so every
        label on the chart would be wrong by name.
        """
        bucket = func.date_trunc(
            "day", func.timezone(TASHKENT.key, CallModel.started_at)
        )
        statement = (
            select(
                bucket.label("day"),
                _count(_INCOMING).label("inbound"),
                _count(_INCOMING, _ANSWERED).label("inbound_answered"),
                _count(_MISSED).label("missed"),
                _count(_OUTGOING).label("outbound"),
                _count(_OUTGOING, _NO_ANSWER).label("outbound_no_answer"),
            )
            .join(AgentModel, AgentModel.id == CallModel.agent_id)
            .where(
                CallModel.started_at >= window.since,
                CallModel.started_at < window.until,
                AgentModel.archived_at.is_(None),
            )
            .group_by(bucket)
            .order_by(bucket)
        )
        if agents is not None:
            statement = statement.where(CallModel.agent_id.in_(agents))

        found = {}
        for row in await self.session.execute(statement):
            day = row.day.date() if hasattr(row.day, "date") else row.day
            found[day] = ActivityDay(
                day=day,
                inbound=int(row.inbound or 0),
                inbound_answered=int(row.inbound_answered or 0),
                missed=int(row.missed or 0),
                outbound=int(row.outbound or 0),
                outbound_no_answer=int(row.outbound_no_answer or 0),
            )
        return [
            found.get(day) or ActivityDay(day=day)
            for day in day_span(window.date_from, window.date_to)
        ]

    # ── Hour of day ───────────────────────────────────────────

    async def _hours(
        self, window: Window, agents: list[uuid.UUID] | None
    ) -> list[ActivityHour]:
        """Volume and missed calls by hour of the LOCAL day.

        ⚠️ Computing this in UTC destroys the conclusion: "customers cannot
        get through at lunchtime" is visible at 12:00 and becomes a
        meaningless 07:00 in UTC. Uzbekistan has no daylight saving, so the
        shift is always +5 — which is exactly why it is so easy to get wrong
        and never notice.

        ⚠️ Same columns as the daily cut, for the reason in
        ``rules.ActivityHour``.
        """
        hour = func.extract(
            "hour", func.timezone(TASHKENT.key, CallModel.started_at)
        ).cast(Integer)
        statement = (
            select(
                hour.label("hour"),
                _count(_INCOMING).label("inbound"),
                _count(_INCOMING, _ANSWERED).label("inbound_answered"),
                _count(_MISSED).label("missed"),
                _count(_OUTGOING).label("outbound"),
                _count(_OUTGOING, _NO_ANSWER).label("outbound_no_answer"),
            )
            .join(AgentModel, AgentModel.id == CallModel.agent_id)
            .where(
                CallModel.started_at >= window.since,
                CallModel.started_at < window.until,
                AgentModel.archived_at.is_(None),
            )
            .group_by(hour)
        )
        if agents is not None:
            statement = statement.where(CallModel.agent_id.in_(agents))

        found = {
            int(row.hour): ActivityHour(
                hour=int(row.hour),
                inbound=int(row.inbound or 0),
                inbound_answered=int(row.inbound_answered or 0),
                missed=int(row.missed or 0),
                outbound=int(row.outbound or 0),
                outbound_no_answer=int(row.outbound_no_answer or 0),
            )
            for row in await self.session.execute(statement)
        }
        # Empty hours come back as well, so the chart has no gap in it.
        return [found.get(hour) or ActivityHour(hour=hour) for hour in WORK_HOURS]

    # ── Callbacks ─────────────────────────────────────────────

    def _missed_by_customer(
        self, window: Window, agents: list[uuid.UUID] | None, per_agent: bool
    ):
        """Missed incoming calls grouped by customer (and optionally agent).

        ``per_agent=False`` groups by number ALONE and returns one aggregate
        row: for the company total, one customer who rang two employees is one
        person.
        """
        agent_column = (
            CallModel.agent_id
            if per_agent
            # The aggregate mode has no agent column, but the code below
            # expects the same shape — so the nil UUID stands in for one.
            else literal_column("'00000000-0000-0000-0000-000000000000'::uuid")
        )
        statement = (
            select(
                agent_column.label("agent_id"),
                _TAIL.label("tail"),
                func.max(CallModel.started_at).label("last_missed"),
                func.count(CallModel.id).label("attempts"),
            )
            .join(AgentModel, AgentModel.id == CallModel.agent_id)
            .where(
                _MISSED,
                CallModel.started_at >= window.since,
                CallModel.started_at < window.until,
                AgentModel.archived_at.is_(None),
                # A missed call with no usable number cannot be returned —
                # there is nobody to call. Counting it as "not called back"
                # blames the employee for something impossible, so it is left
                # out of this cut and still shows in the volume columns.
                _TAIL.is_not(None),
            )
            .group_by(*([CallModel.agent_id, _TAIL] if per_agent else [_TAIL]))
        )
        if agents is not None:
            statement = statement.where(CallModel.agent_id.in_(agents))
        return statement

    @staticmethod
    def _first_contact(missed):
        """The earliest contact after a customer's LAST missed attempt.

        ════════════════════════════════════════════════════════
         THREE DECISIONS TO READ HERE
        ════════════════════════════════════════════════════════

        1. COUNTED PER CUSTOMER, not per event. A customer who cannot get
           through tries again — measured, 1.8 times on average (384 events
           from 216 people). Counting events counts one person's problem
           several times.

        2. THE CLOCK STARTS AT THE CUSTOMER'S **LAST** MISSED ATTEMPT.
           Starting from the first would be wrong: a customer who rang at
           09:00 and again at 18:00 and was called back at 09:20 would read as
           "reached", while the 18:00 attempt is still unanswered.

        3. CONTACT IS EITHER DIRECTION, and both count:
             · somebody called the customer back (outgoing), or
             · the customer tried again and WAS ANSWERED this time.
           Leaving the second out would report the commonest real case —
           "they rang again and we spoke" — as "never reached".

           WHO made contact is not checked: if a colleague returned the call
           the customer was still served (measured: 9 % of the time). The
           missed call itself is still attributed to the employee whose phone
           rang — that is where the responsibility lies.
        """
        return (
            select(CallModel.started_at.label("at"))
            .where(
                _TAIL == missed.c.tail,
                CallModel.started_at > missed.c.last_missed,
                CallModel.started_at
                <= missed.c.last_missed + timedelta(hours=CALLBACK_WINDOW_HOURS),
                or_(_OUTGOING, _ANSWERED),
            )
            .order_by(CallModel.started_at)
            .limit(1)
            .lateral("c")
        )

    async def _callbacks(
        self,
        window: Window,
        agents: list[uuid.UUID] | None,
        per_agent: bool = True,
    ) -> CallbackStats:
        """How many unreached customers were contacted afterwards."""
        missed = self._missed_by_customer(window, agents, per_agent).subquery("m")
        contact = self._first_contact(missed)
        at = literal_column("c.at")

        statement = (
            select(
                missed.c.agent_id,
                func.count().label("clients"),
                func.count(at).label("reached"),
                func.coalesce(func.sum(missed.c.attempts), 0).label("addressable"),
                # A customer who was contacted closes ALL of their missed
                # events: four attempts and one answer means four resolved.
                func.coalesce(
                    func.sum(case((at.is_not(None), missed.c.attempts), else_=0)), 0
                ).label("events_closed"),
                func.percentile_cont(0.5)
                .within_group(func.extract("epoch", at - missed.c.last_missed) / 60)
                .label("median_minutes"),
            )
            .select_from(missed.outerjoin(contact, text("true")))
            .group_by(missed.c.agent_id)
        )
        rows = (await self.session.execute(statement)).all()

        # ⚠️ THE OVERALL MEDIAN IS A SEPARATE, UNGROUPED QUERY.
        #
        # It used to be taken from the grouped one above — a median per agent,
        # and then Python's median OF THOSE. A "median of medians" ignores
        # volume: one employee who returned 300 calls in 3 minutes and three
        # who each returned one in 120 minutes gives ~120, where the true
        # median is near 3. Measured at BonviZvonki: 4.2 reported against 4.75
        # actual.
        overall = select(
            func.percentile_cont(0.5)
            .within_group(func.extract("epoch", at - missed.c.last_missed) / 60)
            .label("median_minutes")
        ).select_from(missed.outerjoin(contact, text("true")))
        median = (await self.session.execute(overall)).scalar_one_or_none()

        return CallbackStats(
            clients={row.agent_id: int(row.clients or 0) for row in rows},
            reached={row.agent_id: int(row.reached or 0) for row in rows},
            events_closed={row.agent_id: int(row.events_closed or 0) for row in rows},
            addressable={row.agent_id: int(row.addressable or 0) for row in rows},
            medians={
                row.agent_id: round(float(row.median_minutes), 1)
                for row in rows
                if row.median_minutes is not None
            },
            median_minutes=round(float(median), 1) if median is not None else None,
        )

    # ── One agent's unreached customers ───────────────────────

    async def missed_clients(
        self, agent_id: uuid.UUID, window: Window
    ) -> list[MissedClient]:
        """The customers who could not get through to one employee.

        ⚠️ THE LOGIC MUST BE IDENTICAL TO THE SUMMARY: same window, same
        matching key, same definition of contact, same starting point (the
        customer's LAST missed attempt). Otherwise the detail contradicts the
        total and the tool built to prove a number is what destroys trust in
        it.

        Unreached customers sort FIRST: the list is a work list, so what still
        needs doing has to be at the top.
        """
        missed = (
            select(
                _TAIL.label("tail"),
                func.min(CallModel.contact_name).label("contact_name"),
                func.count(CallModel.id).label("attempts"),
                func.min(CallModel.started_at).label("first_missed"),
                func.max(CallModel.started_at).label("last_missed"),
            )
            .where(
                CallModel.agent_id == agent_id,
                _MISSED,
                CallModel.started_at >= window.since,
                CallModel.started_at < window.until,
                _TAIL.is_not(None),
            )
            .group_by(_TAIL)
            .subquery("m")
        )

        # Who made contact, and which way round. A different employee is a
        # perfectly good answer and the list says so by name.
        agent = aliased(AgentModel)
        contact = (
            select(
                CallModel.started_at.label("at"),
                agent.full_name.label("by_name"),
                CallModel.direction.label("dir"),
            )
            .join(agent, agent.id == CallModel.agent_id)
            .where(
                _TAIL == missed.c.tail,
                CallModel.started_at > missed.c.last_missed,
                CallModel.started_at
                <= missed.c.last_missed + timedelta(hours=CALLBACK_WINDOW_HOURS),
                or_(_OUTGOING, _ANSWERED),
            )
            .order_by(CallModel.started_at)
            .limit(1)
            .lateral("c")
        )

        at = literal_column("c.at")
        statement = (
            select(
                missed.c.tail,
                missed.c.contact_name,
                missed.c.attempts,
                missed.c.first_missed,
                missed.c.last_missed,
                at.label("contacted_at"),
                literal_column("c.by_name").label("contacted_by"),
                literal_column("c.dir").label("contact_dir"),
            )
            .select_from(missed.outerjoin(contact, text("true")))
            .order_by(at.is_not(None), missed.c.last_missed.desc())
        )

        return [
            MissedClient(
                phone_key=row.tail,
                contact_name=row.contact_name,
                attempts=int(row.attempts or 0),
                first_missed_at=row.first_missed,
                last_missed_at=row.last_missed,
                contacted_at=row.contacted_at,
                contacted_by=row.contacted_by,
                contact_inbound=(
                    None
                    if row.contact_dir is None
                    else str(row.contact_dir) == CallDirection.INCOMING.value
                ),
            )
            for row in await self.session.execute(statement)
        ]

    async def agent_name(self, agent_id: uuid.UUID) -> str | None:
        """One live agent's display name, or None. A projection, never the entity.

        ⚠️ ARCHIVED AGENTS ARE EXCLUDED HERE TOO. The summary leaves them out
        (``_per_agent``), so an archived employee never appears in the table and
        cannot be clicked — but a hand-typed URL would otherwise open a detail
        list for somebody the report does not contain, which is the very
        "detail disagrees with the summary" this module keeps warning about.
        BonviZvonki's detail endpoint does a plain ``session.get`` and answers.
        """
        return await self.session.scalar(
            select(AgentModel.full_name).where(
                AgentModel.id == agent_id, AgentModel.archived_at.is_(None)
            )
        )


__all__ = ["ActivityService", "CallbackStats", "FLEET_WIDE"]
