"""SQLAlchemy base, session and the DDL helpers models share (CONVENTIONS.md §10).

Three things live here and nothing else:

* :class:`Base` plus :class:`UUIDMixin` / :class:`TimestampMixin` — the shape
  every model starts from;
* the async engine and session factory, created lazily so the test suite can
  point the process at ``bonvicall_test`` before anything connects (§13);
* :func:`phone_key_computed`, the generated-column helper, so that the last-9
  rule reaches the database from ``core/phone.py`` and from nowhere else (§7).

``Base.metadata.create_all`` is not used anywhere in this project. The schema
comes from one real Alembic history, including in tests, which is what makes
``alembic upgrade head`` exercised on every single suite run (§10, §13).
"""

from __future__ import annotations

import uuid
from collections.abc import AsyncIterator
from datetime import datetime
from functools import lru_cache

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql.elements import ColumnElement

from src.core.config import get_settings
from src.core.phone import phone_key_sql

#: Deterministic names for anything we do not name by hand. Without this,
#: Alembic autogenerate invents names that differ between machines and a
#: constraint can then be dropped under one name and recreated under another.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base. Every ORM model in the product inherits from this one."""

    metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)


class UUIDMixin:
    """A ``uuid4`` primary key, generated by the application.

    Application-side generation matters for the device API: the server can
    return an id inside the same transaction that wrote the row, and an id is
    never guessable from a neighbouring one.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        doc="Primary key, generated by the application at insert time.",
    )


class TimestampMixin:
    """``created_at`` / ``updated_at``, both from the database clock.

    ``func.now()`` rather than a Python value: rows written by a job, by a
    migration and by a request must all be comparable, and only the database
    clock is common to all three (N36).
    """

    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        doc="When the server first wrote this row.",
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        onupdate=sa.func.now(),
        doc="When the server last changed this row.",
    )


def sql_text(expression: ColumnElement) -> str:
    """Render a SQLAlchemy expression as literal PostgreSQL, for DDL."""
    return str(
        expression.compile(
            dialect=postgresql.dialect(),
            compile_kwargs={"literal_binds": True},
        )
    )


def phone_key_computed(source_column: str) -> sa.Computed:
    """A ``GENERATED ALWAYS AS (...) STORED`` last-9 key over ``source_column``.

    The expression is produced by ``core.phone.phone_key_sql`` — the same
    function the application uses — so the stored key and the Python key cannot
    drift. If they ever did, every join on the key would silently return no
    rows: no error, no clue (CONVENTIONS.md §7).

    Generated rather than written by the application because a value the
    database derives cannot be forgotten by a new code path (SPEC §3.0).
    """
    return sa.Computed(sql_text(phone_key_sql(sa.column(source_column))), persisted=True)


@lru_cache(maxsize=1)
def get_engine() -> AsyncEngine:
    """The process-wide async engine."""
    settings = get_settings()
    return create_async_engine(
        settings.database_url,
        echo=settings.db_echo,
        pool_size=settings.db_pool_size,
        max_overflow=settings.db_max_overflow,
        pool_pre_ping=True,
    )


@lru_cache(maxsize=1)
def get_sessionmaker() -> async_sessionmaker[AsyncSession]:
    """The process-wide session factory."""
    return async_sessionmaker(
        bind=get_engine(),
        expire_on_commit=False,
        autoflush=False,
    )


async def ping(session: AsyncSession) -> bool:
    """True when the database answers. Used by ``GET /readyz``.

    It lives here rather than in the health router because a router may not
    contain SQL (CONVENTIONS.md §2), and "can we reach the database" is an
    infrastructure question that belongs to no module.
    """
    try:
        await session.execute(sa.text("SELECT 1"))
        return True
    except Exception:  # any driver-level failure: unreachable, in recovery, out of connections
        return False


async def session_scope() -> AsyncIterator[AsyncSession]:
    """One session per request. The service layer owns the commit (§2)."""
    async with get_sessionmaker()() as session:
        try:
            yield session
        except Exception:
            await session.rollback()
            raise


__all__ = [
    "NAMING_CONVENTION",
    "Base",
    "TimestampMixin",
    "UUIDMixin",
    "get_engine",
    "get_sessionmaker",
    "phone_key_computed",
    "ping",
    "session_scope",
    "sql_text",
]
