package uz.bonvi.call.arch

import com.google.common.truth.Truth.assertThat
import com.google.common.truth.Truth.assertWithMessage
import org.json.JSONObject
import org.junit.Test
import uz.bonvi.call.TestPaths
import uz.bonvi.call.data.local.BonviCallDatabase
import java.io.File

/**
 * The migration matches the schema Room actually generated.
 *
 * ═══ Why this is checked from the exported JSON ════════════════════════════
 * `fallbackToDestructiveMigration` is forbidden in this app, because what it
 * would destroy is the upload queue — calls that happened, were recorded, and
 * have not reached the server yet (N8). The consequence is that a migration
 * which does not produce EXACTLY the schema Room expects crashes the app at
 * startup on every phone that already has a database, and a phone that cannot
 * open its database cannot drain the queue it is holding.
 *
 * Room's own `MigrationTestHelper` needs an instrumented run on a device. This
 * does not: the JSON under `app/schemas` is generated by the compiler on every build,
 * so comparing the migration's SQL against it catches the drift that matters —
 * a column added to an entity and forgotten in the migration.
 */
class RoomMigrationTest {

    private val schemaDir = File(
        TestPaths.appDir,
        "schemas/uz.bonvi.call.data.local.BonviCallDatabase",
    )

    private val migrationSource: String by lazy {
        TestPaths.kotlinSources().single { it.name == "DatabaseModule.kt" }.readText()
    }

    /**
     * The same file with comments removed.
     *
     * The comment above the builder says "NO fallbackToDestructiveMigration()",
     * which is the rule being enforced — a check that fired on it would make
     * the explanation unwritable, and the explanation is what stops the next
     * person adding the call.
     */
    private val migrationCode: String by lazy {
        migrationSource
            .replace(Regex("""/\*.*?\*/""", RegexOption.DOT_MATCHES_ALL), " ")
            .replace(Regex("""//.*$""", RegexOption.MULTILINE), " ")
    }

    private fun schema(version: Int): JSONObject {
        val file = File(schemaDir, "$version.json")
        assertWithMessage("$file was not exported — is exportSchema still on?")
            .that(file.isFile).isTrue()
        return JSONObject(file.readText()).getJSONObject("database")
    }

    private fun columnsOf(version: Int, table: String): List<String> {
        val entities = schema(version).getJSONArray("entities")
        for (index in 0 until entities.length()) {
            val entity = entities.getJSONObject(index)
            if (entity.getString("tableName") != table) continue
            val fields = entity.getJSONArray("fields")
            return (0 until fields.length()).map { fields.getJSONObject(it).getString("columnName") }
        }
        error("$table is not in schema version $version")
    }

    @Test
    fun `the exported schema exists for the current version`() {
        assertThat(schema(BonviCallDatabase.VERSION).getInt("version"))
            .isEqualTo(BonviCallDatabase.VERSION)
    }

    @Test
    fun `every version step has a migration`() {
        // A gap here is a phone that cannot open its own database. The version
        // is bumped in one file and the migration written in another, which is
        // exactly the pair that drifts.
        for (from in 1 until BonviCallDatabase.VERSION) {
            assertWithMessage("No MIGRATION_${from}_${from + 1} in DatabaseModule")
                .that(migrationSource).contains("MIGRATION_${from}_${from + 1}")
            assertWithMessage("MIGRATION_${from}_${from + 1} is written but never registered")
                .that(migrationSource).contains(".addMigrations(")
        }
    }

    @Test
    fun `migration 1 to 2 creates every column the entities declare`() {
        // audio_jobs is new in 2; pending_calls gained three columns. Both are
        // compared against what Room generated rather than against the entity
        // source, because Room is what will refuse to open the database.
        for (column in columnsOf(2, "audio_jobs")) {
            assertWithMessage("audio_jobs.$column is missing from MIGRATION_1_2")
                .that(migrationSource).contains(column)
        }

        val added = columnsOf(2, "pending_calls") - columnsOf(1, "pending_calls").toSet()
        assertThat(added).isNotEmpty()
        for (column in added) {
            assertWithMessage("pending_calls.$column is missing from MIGRATION_1_2")
                .that(migrationSource).contains("ADD COLUMN $column")
        }
    }

    @Test
    fun `no migration drops or rewrites a table`() {
        // Every row in this database is a call that happened. A migration that
        // recreates a table to change it is how the queue is lost while the
        // schema ends up looking right.
        for (forbidden in listOf("DROP TABLE", "DELETE FROM", "fallbackToDestructiveMigration")) {
            assertWithMessage("DatabaseModule contains `$forbidden`")
                .that(migrationCode).doesNotContain(forbidden)
        }
    }
}
