"""Registered numbers and their time-boxed assignment to agents (SPEC §3.3).

This is the identity anchor of the whole product: capture, attribution and the
privacy boundary are all decided against the **registered number**, never
against the device.

Two constraints in the migration carry the weight, and neither can be done in
Python: the ``phone_key`` uniqueness (one number typed three ways is one row)
and the ``EXCLUDE USING gist`` overlap check on assignments (two admins
clicking at once must not fork the anchor).
"""

from __future__ import annotations

import uuid
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Mapped, mapped_column

from src.core.database import Base, TimestampMixin, UUIDMixin, phone_key_computed

#: R10: the panel must show which SIM relationships are not Bonvi's to keep.
SIM_OWNER_COMPANY = "company"
SIM_OWNER_EMPLOYEE = "employee"


class RegisteredNumberModel(Base, UUIDMixin, TimestampMixin):
    """A company line, independent of whoever currently holds it."""

    __tablename__ = "registered_numbers"

    e164: Mapped[str] = mapped_column(
        sa.String(20),
        nullable=False,
        doc="Normalised on write by core.phone.to_e164, e.g. '+998901112233'.",
    )
    phone_key: Mapped[str] = mapped_column(
        sa.CHAR(9),
        phone_key_computed("e164"),
        nullable=False,
        doc=(
            "Last 9 digits, generated by the database from e164 (N37). This is "
            "the uniqueness that matters: a number typed in three formats is "
            "one row. Generated rather than assigned so it cannot drift."
        ),
    )
    operator: Mapped[str | None] = mapped_column(
        sa.String(32),
        nullable=True,
        doc=(
            "beeline | ucell | mobiuz | uzmobile | other. Free-form on purpose: "
            "it is a reporting axis for the per-operator callback table (R19), "
            "not a control."
        ),
    )
    sim_owner: Mapped[str] = mapped_column(
        sa.String(16),
        nullable=False,
        server_default=SIM_OWNER_COMPANY,
        doc="company | employee. R10: which relationships Bonvi cannot reclaim.",
    )
    label: Mapped[str | None] = mapped_column(
        sa.String(64), nullable=True, doc="Admin's own label for the line."
    )
    is_active: Mapped[bool] = mapped_column(
        sa.Boolean,
        nullable=False,
        server_default=sa.true(),
        doc="False when the line is out of service. History stays.",
    )

    __table_args__ = (
        sa.UniqueConstraint("phone_key", name="uq_registered_numbers_phone_key"),
        sa.CheckConstraint(
            "sim_owner IN ('company', 'employee')", name="sim_owner_known"
        ),
        sa.Index("ix_registered_numbers_active", "is_active", "e164"),
    )


class NumberAssignmentModel(Base, UUIDMixin, TimestampMixin):
    """Who held a number, from when to when (UC-07).

    Attribution rule (D-08), stated once: a call belongs to the assignment
    whose ``[valid_from, valid_to)`` contains ``calls.started_at`` — the call's
    own start, not the upload time and not the server receipt time. A call made
    before a SIM handover stays with agent A even if the old phone only comes
    online a week later.
    """

    __tablename__ = "number_assignments"

    number_id: Mapped[uuid.UUID] = mapped_column(
        postgresql.UUID(as_uuid=True),
        sa.ForeignKey("registered_numbers.id", ondelete="RESTRICT"),
        nullable=False,
        doc="The line. RESTRICT: a number with history is never deleted.",
    )
    agent_id: Mapped[uuid.UUID] = mapped_column(
        postgresql.UUID(as_uuid=True),
        sa.ForeignKey("agents.id", ondelete="RESTRICT"),
        nullable=False,
        doc="Who held it. RESTRICT: an agent with attributed calls is archived, not deleted.",
    )
    valid_from: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, doc="Inclusive start of the period."
    )
    valid_to: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=True,
        doc="Exclusive end; NULL means open-ended (they hold it now).",
    )
    created_by: Mapped[uuid.UUID] = mapped_column(
        postgresql.UUID(as_uuid=True),
        sa.ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        doc="Which admin made the assignment. Also in audit_log.",
    )
    closed_by: Mapped[uuid.UUID | None] = mapped_column(
        postgresql.UUID(as_uuid=True),
        sa.ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        doc="Which admin closed it.",
    )
    note: Mapped[str | None] = mapped_column(
        sa.String(255), nullable=True, doc="Why the handover happened."
    )

    # The EXCLUDE USING gist constraint that makes overlap impossible is added
    # by the migration: SQLAlchemy can express it, but btree_gist must exist
    # first and the ordering is clearer written out there (T147).
    __table_args__ = (
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="valid_period"
        ),
        sa.Index("ix_assignments_agent_range", "agent_id", sa.text("valid_from DESC")),
        sa.Index("ix_assignments_number_range", "number_id", sa.text("valid_from DESC")),
    )
