/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.AppVariant

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param variant 
 * @param version 
 * @param versionCode 
 */


data class AppInfoIn (

    @Json(name = "variant")
    val variant: AppVariant,

    @Json(name = "version")
    val version: kotlin.String,

    @Json(name = "version_code")
    val versionCode: kotlin.Int

) {


}

