/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The ``targetSdk`` product flavour (D-06).  Reported on every heartbeat, stored on every call, so capture rate is measurable per variant and not only per handset model.
 *
 * Values: LEGACY28,MODERN34
 */

@JsonClass(generateAdapter = false)
enum class AppVariant(val value: kotlin.String) {

    @Json(name = "legacy28")
    LEGACY28("legacy28"),

    @Json(name = "modern34")
    MODERN34("modern34");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AppVariant) "$data" else null

        /**
         * Returns a valid [AppVariant] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AppVariant? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

