/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Opus is the target; AAC-LC is the decided fallback and is counted (§7.6).
 *
 * Values: OPUS,AAC_LC
 */

@JsonClass(generateAdapter = false)
enum class AudioCodec(val value: kotlin.String) {

    @Json(name = "opus")
    OPUS("opus"),

    @Json(name = "aac_lc")
    AAC_LC("aac_lc");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AudioCodec) "$data" else null

        /**
         * Returns a valid [AudioCodec] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AudioCodec? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

