/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Why a call has no audio. Closed, ``NOT NULL`` whenever audio is absent (N5).  UC-14 names six; SPEC §3.9 justifies the other four one by one. The gap report's denominator excludes ``pending_upload`` and ``not_expected``, which is what keeps \"% of answered calls with audio\" honest.
 *
 * Values: PENDING_UPLOAD,NOT_EXPECTED,RECORDING_ROUTE_UNAVAILABLE,OEM_RECORDER_OFF,NO_PERMISSION,CAPTURE_RETURNED_SILENCE,APP_NOT_RUNNING,UPLOAD_EXPIRED,QUEUE_SPACE_EXHAUSTED,ATTRIBUTION_FAILED
 */

@JsonClass(generateAdapter = false)
enum class AudioMissingReason(val value: kotlin.String) {

    @Json(name = "pending_upload")
    PENDING_UPLOAD("pending_upload"),

    @Json(name = "not_expected")
    NOT_EXPECTED("not_expected"),

    @Json(name = "recording_route_unavailable")
    RECORDING_ROUTE_UNAVAILABLE("recording_route_unavailable"),

    @Json(name = "oem_recorder_off")
    OEM_RECORDER_OFF("oem_recorder_off"),

    @Json(name = "no_permission")
    NO_PERMISSION("no_permission"),

    @Json(name = "capture_returned_silence")
    CAPTURE_RETURNED_SILENCE("capture_returned_silence"),

    @Json(name = "app_not_running")
    APP_NOT_RUNNING("app_not_running"),

    @Json(name = "upload_expired")
    UPLOAD_EXPIRED("upload_expired"),

    @Json(name = "queue_space_exhausted")
    QUEUE_SPACE_EXHAUSTED("queue_space_exhausted"),

    @Json(name = "attribution_failed")
    ATTRIBUTION_FAILED("attribution_failed");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AudioMissingReason) "$data" else null

        /**
         * Returns a valid [AudioMissingReason] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AudioMissingReason? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

