/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * UC-11's five classes are direction x disposition.  ``missed`` and ``rejected`` are incoming-only, ``no_answer`` is outgoing-only — enforced by a CHECK, so the invalid combinations are unrepresentable rather than merely unused.
 *
 * Values: ANSWERED,MISSED,REJECTED,NO_ANSWER
 */

@JsonClass(generateAdapter = false)
enum class CallDisposition(val value: kotlin.String) {

    @Json(name = "answered")
    ANSWERED("answered"),

    @Json(name = "missed")
    MISSED("missed"),

    @Json(name = "rejected")
    REJECTED("rejected"),

    @Json(name = "no_answer")
    NO_ANSWER("no_answer");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CallDisposition) "$data" else null

        /**
         * Returns a valid [CallDisposition] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CallDisposition? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

