/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Ours, not BonviZvonki's ``inbound``/``outbound``.  The export (SPEC §4.9) maps ours onto theirs in exactly one place, so the two vocabularies never leak into each other.
 *
 * Values: INCOMING,OUTGOING
 */

@JsonClass(generateAdapter = false)
enum class CallDirection(val value: kotlin.String) {

    @Json(name = "incoming")
    INCOMING("incoming"),

    @Json(name = "outgoing")
    OUTGOING("outgoing");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CallDirection) "$data" else null

        /**
         * Returns a valid [CallDirection] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CallDirection? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

