/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``granted_not_working`` is the OEM-permission-manager case UC-03 names.
 *
 * Values: GRANTED_WORKING,GRANTED_NOT_WORKING,DENIED,DENIED_PERMANENTLY,NOT_APPLICABLE,UNKNOWN
 */

@JsonClass(generateAdapter = false)
enum class CapabilityState(val value: kotlin.String) {

    @Json(name = "granted_working")
    GRANTED_WORKING("granted_working"),

    @Json(name = "granted_not_working")
    GRANTED_NOT_WORKING("granted_not_working"),

    @Json(name = "denied")
    DENIED("denied"),

    @Json(name = "denied_permanently")
    DENIED_PERMANENTLY("denied_permanently"),

    @Json(name = "not_applicable")
    NOT_APPLICABLE("not_applicable"),

    @Json(name = "unknown")
    UNKNOWN("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CapabilityState) "$data" else null

        /**
         * Returns a valid [CapabilityState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CapabilityState? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

