/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One row per installation per capability (UC-03, §7.8).  Every one of these is verified by exercising it, never by reading a permission flag — that is what makes ``granted_not_working`` expressible.
 *
 * Values: PHONE_STATE,CALL_LOG,MICROPHONE,CONTACTS,NOTIFICATIONS,CALL_PHONE,BATTERY_EXEMPTION,STORAGE_ACCESS,OEM_AUTOSTART,FOREGROUND_SERVICE,OEM_RECORDER,SUBSCRIPTION_RESOLUTION
 */

@JsonClass(generateAdapter = false)
enum class Capability(val value: kotlin.String) {

    @Json(name = "phone_state")
    PHONE_STATE("phone_state"),

    @Json(name = "call_log")
    CALL_LOG("call_log"),

    @Json(name = "microphone")
    MICROPHONE("microphone"),

    @Json(name = "contacts")
    CONTACTS("contacts"),

    @Json(name = "notifications")
    NOTIFICATIONS("notifications"),

    @Json(name = "call_phone")
    CALL_PHONE("call_phone"),

    @Json(name = "battery_exemption")
    BATTERY_EXEMPTION("battery_exemption"),

    @Json(name = "storage_access")
    STORAGE_ACCESS("storage_access"),

    @Json(name = "oem_autostart")
    OEM_AUTOSTART("oem_autostart"),

    @Json(name = "foreground_service")
    FOREGROUND_SERVICE("foreground_service"),

    @Json(name = "oem_recorder")
    OEM_RECORDER("oem_recorder"),

    @Json(name = "subscription_resolution")
    SUBSCRIPTION_RESOLUTION("subscription_resolution");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Capability) "$data" else null

        /**
         * Returns a valid [Capability] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Capability? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

