/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Which mechanism produced the recording (S1, the M0 baseline).  ``NONE`` may only appear with ``has_audio = false``.
 *
 * Values: OEM_FILE_HARVEST,APP_VOICE_RECOGNITION,APP_VOICE_COMMUNICATION,APP_MIC,NONE
 */

@JsonClass(generateAdapter = false)
enum class CaptureRoute(val value: kotlin.String) {

    @Json(name = "oem_file_harvest")
    OEM_FILE_HARVEST("oem_file_harvest"),

    @Json(name = "app_voice_recognition")
    APP_VOICE_RECOGNITION("app_voice_recognition"),

    @Json(name = "app_voice_communication")
    APP_VOICE_COMMUNICATION("app_voice_communication"),

    @Json(name = "app_mic")
    APP_MIC("app_mic"),

    @Json(name = "none")
    NONE("none");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CaptureRoute) "$data" else null

        /**
         * Returns a valid [CaptureRoute] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CaptureRoute? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

