/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``200`` for an accepted chunk.
 *
 * @param receivedBytes 
 */


data class ChunkAcceptedOut (

    @Json(name = "received_bytes")
    val receivedBytes: kotlin.Int

) {


}

