/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Server-to-device commands. No ``send_sms`` — SMS is out of scope.
 *
 * Values: DIAL,CONFIG,LOGOUT,PING,RECHECK
 */

@JsonClass(generateAdapter = false)
enum class CommandKind(val value: kotlin.String) {

    @Json(name = "dial")
    DIAL("dial"),

    @Json(name = "config")
    CONFIG("config"),

    @Json(name = "logout")
    LOGOUT("logout"),

    @Json(name = "ping")
    PING("ping"),

    @Json(name = "recheck")
    RECHECK("recheck");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CommandKind) "$data" else null

        /**
         * Returns a valid [CommandKind] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CommandKind? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

