/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``200``, and **idempotent**: committing twice returns the same body.  Only after this response does the device delete its local file (N11).
 *
 * @param audioId 
 * @param bytes 
 * @param durationMismatch The file's length differs from the call log's by > 2 s (UC-14).
 * @param sha256 
 * @param stored 
 */


data class CommitOut (

    @Json(name = "audio_id")
    val audioId: java.util.UUID,

    @Json(name = "bytes")
    val bytes: kotlin.Int,

    /* The file's length differs from the call log's by > 2 s (UC-14). */
    @Json(name = "duration_mismatch")
    val durationMismatch: kotlin.Boolean,

    @Json(name = "sha256")
    val sha256: kotlin.String,

    @Json(name = "stored")
    val stored: kotlin.Boolean

) {


}

