/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Why a command did not happen. UC-16 requires the panel to say which.
 *
 * Values: DEVICE_OFFLINE,NO_PERMISSION,OS_REFUSED,ACK_TIMEOUT,DISCARDED_STALE,UNSUPPORTED,BUSY
 */

@JsonClass(generateAdapter = false)
enum class CommandFailureReason(val value: kotlin.String) {

    @Json(name = "device_offline")
    DEVICE_OFFLINE("device_offline"),

    @Json(name = "no_permission")
    NO_PERMISSION("no_permission"),

    @Json(name = "os_refused")
    OS_REFUSED("os_refused"),

    @Json(name = "ack_timeout")
    ACK_TIMEOUT("ack_timeout"),

    @Json(name = "discarded_stale")
    DISCARDED_STALE("discarded_stale"),

    @Json(name = "unsupported")
    UNSUPPORTED("unsupported"),

    @Json(name = "busy")
    BUSY("busy");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CommandFailureReason) "$data" else null

        /**
         * Returns a valid [CommandFailureReason] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CommandFailureReason? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

