/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * What the employee's own-calls screen says about one call's recording.  A **derived** value, not a column: ``has_audio`` and ``audio_missing_reason`` together answer it, and the app needs one non-null thing to switch on.  It is deliberately not a value added to :class:`AudioMissingReason`. Every member of that enum means audio is *absent* — its own docstring says \"NOT NULL whenever audio is absent\" — so a ``recorded`` member would make the name a lie and would arrive as an unparseable value in every client already generated against it.
 *
 * Values: RECORDED,EXPIRED,QUEUED,NOT_EXPECTED,MISSING
 */

@JsonClass(generateAdapter = false)
enum class DeviceAudioState(val value: kotlin.String) {

    @Json(name = "recorded")
    RECORDED("recorded"),

    @Json(name = "expired")
    EXPIRED("expired"),

    @Json(name = "queued")
    QUEUED("queued"),

    @Json(name = "not_expected")
    NOT_EXPECTED("not_expected"),

    @Json(name = "missing")
    MISSING("missing");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DeviceAudioState) "$data" else null

        /**
         * Returns a valid [DeviceAudioState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DeviceAudioState? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

