/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

// PATCHED by android/scripts/widen_int64.py: the contract declares this
// field as a formatless integer, which generates as a 32-bit kotlin.Int
// and cannot hold its real range. Delete the patch once the server emits
// format: int64 — Int64WireContractTest says when.

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.AppInfoIn
import uz.bonvi.call.data.remote.dto.DeviceInfoIn

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``POST /api/device/v1/enrolment/redeem`` — public, rate-limited.
 *
 * @param app 
 * @param code 
 * @param device 
 * @param deviceEpochMs 
 * @param deviceFingerprint 
 * @param deviceTimezone 
 * @param simSlot 
 * @param simSubscriptionId 
 */


data class DeviceRedeemIn (

    @Json(name = "app")
    val app: AppInfoIn,

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "device")
    val device: DeviceInfoIn,

    @Json(name = "device_epoch_ms")
    val deviceEpochMs: kotlin.Long,

    @Json(name = "device_fingerprint")
    val deviceFingerprint: kotlin.String,

    @Json(name = "device_timezone")
    val deviceTimezone: kotlin.String,

    @Json(name = "sim_slot")
    val simSlot: kotlin.Int? = null,

    @Json(name = "sim_subscription_id")
    val simSubscriptionId: kotlin.Int? = null

) {


}

