/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``POST /api/device/v1/enrolment/verify/callback/start`` — route 2.
 *
 * @param callbackMsisdn 
 * @param expiresAt 
 * @param verificationId 
 * @param pollAfterMs 
 */


data class DeviceCallbackStartOut (

    @Json(name = "callback_msisdn")
    val callbackMsisdn: kotlin.String,

    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime,

    @Json(name = "verification_id")
    val verificationId: java.util.UUID,

    @Json(name = "poll_after_ms")
    val pollAfterMs: kotlin.Int? = 2000

) {


}

