/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.InstallationStatus
import uz.bonvi.call.data.remote.dto.RedeemAgentOut
import uz.bonvi.call.data.remote.dto.RedeemNumberOut
import uz.bonvi.call.data.remote.dto.RedeemVerificationOut

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``201``. The provisional token is scoped — an unverified phone cannot upload a single call (SPEC §4.2).
 *
 * @param agent 
 * @param expiresIn 
 * @param installationId 
 * @param number 
 * @param provisionalToken 
 * @param serverTime 
 * @param status 
 * @param verification 
 */


data class DeviceRedeemOut (

    @Json(name = "agent")
    val agent: RedeemAgentOut,

    @Json(name = "expires_in")
    val expiresIn: kotlin.Int,

    @Json(name = "installation_id")
    val installationId: java.util.UUID,

    @Json(name = "number")
    val number: RedeemNumberOut,

    @Json(name = "provisional_token")
    val provisionalToken: kotlin.String,

    @Json(name = "server_time")
    val serverTime: java.time.OffsetDateTime,

    @Json(name = "status")
    val status: InstallationStatus,

    @Json(name = "verification")
    val verification: RedeemVerificationOut

) {


}

