/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.DeviceCallErrorOut

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One item's outcome.  Failure is **per item, not per batch**: a batch that fails wholesale is a batch the device will retry forever (SPEC §4.4 rule 6).
 *
 * @param clientCallId 
 * @param status 
 * @param audioUpload 
 * @param error 
 * @param id 
 */


data class DeviceCallResultOut (

    @Json(name = "client_call_id")
    val clientCallId: java.util.UUID,

    @Json(name = "status")
    val status: DeviceCallResultOut.Status,

    @Json(name = "audio_upload")
    val audioUpload: DeviceCallResultOut.AudioUpload? = null,

    @Json(name = "error")
    val error: DeviceCallErrorOut? = null,

    @Json(name = "id")
    val id: java.util.UUID? = null

) {

    /**
     * 
     *
     * Values: CREATED,UNCHANGED,UPDATED,FAILED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "created") CREATED("created"),
        @Json(name = "unchanged") UNCHANGED("unchanged"),
        @Json(name = "updated") UPDATED("updated"),
        @Json(name = "failed") FAILED("failed");
    }
    /**
     * 
     *
     * Values: REQUIRED,NOT_EXPECTED,ALREADY_PRESENT
     */
    @JsonClass(generateAdapter = false)
    enum class AudioUpload(val value: kotlin.String) {
        @Json(name = "required") REQUIRED("required"),
        @Json(name = "not_expected") NOT_EXPECTED("not_expected"),
        @Json(name = "already_present") ALREADY_PRESENT("already_present");
    }

}

