/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.AudioMissingReason
import uz.bonvi.call.data.remote.dto.CaptureRoute

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The **only** context a device event may carry (§8 rule 5, §15).  Every field is named here, and that is the whole point: the wire schema is the allow-list, so a field the contract does not name cannot leave the phone. An open map — even one whose *values* are typed — leaves the *keys* unconstrained, and the handset belongs to the employee.  ``CONVENTIONS.md`` §8 enforces the same boundary on the Android side with a type signature (``OemHarvestStrategy.locate(Decision.Capture, …)``) so that it cannot be widened in one line. This is the other end of the same pipe, and adding a field here shows up as a diff in ``contract/``.  All optional: one event kind uses two of these, another uses none.
 *
 * @param attempts 
 * @param audioMissingReason 
 * @param byUser 
 * @param captureRoute 
 * @param clientCallId 
 * @param deletedBytes 
 * @param deletedRecords 
 * @param discardedCount 
 * @param freeStorageBytes 
 * @param fromVersion 
 * @param queueBytes 
 * @param queueRecords 
 * @param toVersion 
 */


data class DeviceEventDetailIn (

    @Json(name = "attempts")
    val attempts: kotlin.Int? = null,

    @Json(name = "audio_missing_reason")
    val audioMissingReason: AudioMissingReason? = null,

    @Json(name = "by_user")
    val byUser: kotlin.Boolean? = null,

    @Json(name = "capture_route")
    val captureRoute: CaptureRoute? = null,

    @Json(name = "client_call_id")
    val clientCallId: java.util.UUID? = null,

    @Json(name = "deleted_bytes")
    val deletedBytes: kotlin.Long? = null,

    @Json(name = "deleted_records")
    val deletedRecords: kotlin.Int? = null,

    @Json(name = "discarded_count")
    val discardedCount: kotlin.Int? = null,

    @Json(name = "free_storage_bytes")
    val freeStorageBytes: kotlin.Long? = null,

    @Json(name = "from_version")
    val fromVersion: kotlin.String? = null,

    @Json(name = "queue_bytes")
    val queueBytes: kotlin.Long? = null,

    @Json(name = "queue_records")
    val queueRecords: kotlin.Int? = null,

    @Json(name = "to_version")
    val toVersion: kotlin.String? = null

) {


}

