/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.Attempts
import uz.bonvi.call.data.remote.dto.ByUser
import uz.bonvi.call.data.remote.dto.ClientCallId
import uz.bonvi.call.data.remote.dto.DeletedBytes
import uz.bonvi.call.data.remote.dto.DeletedRecords
import uz.bonvi.call.data.remote.dto.DeviceEventDetailInAudioMissingReason
import uz.bonvi.call.data.remote.dto.DeviceEventDetailInCaptureRoute
import uz.bonvi.call.data.remote.dto.DiscardedCount
import uz.bonvi.call.data.remote.dto.FreeStorageBytes
import uz.bonvi.call.data.remote.dto.FromVersion
import uz.bonvi.call.data.remote.dto.QueueBytes
import uz.bonvi.call.data.remote.dto.QueueRecords
import uz.bonvi.call.data.remote.dto.ToVersion

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The **only** context a device event may carry (§8 rule 5, §15).  Every field is named here, and that is the whole point: the wire schema is the allow-list, so a field the contract does not name cannot leave the phone. An open map — even one whose *values* are typed — leaves the *keys* unconstrained, and the handset belongs to the employee.  ``CONVENTIONS.md`` §8 enforces the same boundary on the Android side with a type signature (``OemHarvestStrategy.locate(Decision.Capture, …)``) so that it cannot be widened in one line. This is the other end of the same pipe, and adding a field here shows up as a diff in ``contract/``.  All optional: one event kind uses two of these, another uses none.
 *
 * @param attempts 
 * @param audioMissingReason 
 * @param byUser 
 * @param captureRoute 
 * @param clientCallId 
 * @param deletedBytes 
 * @param deletedRecords 
 * @param discardedCount 
 * @param freeStorageBytes 
 * @param fromVersion 
 * @param queueBytes 
 * @param queueRecords 
 * @param toVersion 
 */


data class DeviceEventDetailIn (

    @Json(name = "attempts")
    val attempts: Attempts? = null,

    @Json(name = "audio_missing_reason")
    val audioMissingReason: DeviceEventDetailInAudioMissingReason? = null,

    @Json(name = "by_user")
    val byUser: ByUser? = null,

    @Json(name = "capture_route")
    val captureRoute: DeviceEventDetailInCaptureRoute? = null,

    @Json(name = "client_call_id")
    val clientCallId: ClientCallId? = null,

    @Json(name = "deleted_bytes")
    val deletedBytes: DeletedBytes? = null,

    @Json(name = "deleted_records")
    val deletedRecords: DeletedRecords? = null,

    @Json(name = "discarded_count")
    val discardedCount: DiscardedCount? = null,

    @Json(name = "free_storage_bytes")
    val freeStorageBytes: FreeStorageBytes? = null,

    @Json(name = "from_version")
    val fromVersion: FromVersion? = null,

    @Json(name = "queue_bytes")
    val queueBytes: QueueBytes? = null,

    @Json(name = "queue_records")
    val queueRecords: QueueRecords? = null,

    @Json(name = "to_version")
    val toVersion: ToVersion? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

