/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.Capability
import uz.bonvi.call.data.remote.dto.CapabilityState

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One capability report. The result of *exercising* it, never a flag read.
 *
 * @param capability 
 * @param checkedAt 
 * @param state 
 * @param detail 
 */


data class DeviceCapabilityIn (

    @Json(name = "capability")
    val capability: Capability,

    @Json(name = "checked_at")
    val checkedAt: java.time.OffsetDateTime,

    @Json(name = "state")
    val state: CapabilityState,

    @Json(name = "detail")
    val detail: kotlin.String? = null

) {


}

