/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.CommandKind

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A pending command, as the app collects it.
 *
 * @param commandId 
 * @param expiresAt 
 * @param issuedAt 
 * @param kind 
 * @param number 
 */


data class DeviceCommandOut (

    @Json(name = "command_id")
    val commandId: java.util.UUID,

    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime,

    @Json(name = "issued_at")
    val issuedAt: java.time.OffsetDateTime,

    @Json(name = "kind")
    val kind: CommandKind,

    @Json(name = "number")
    val number: kotlin.String? = null

) {


}

