/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

// PATCHED by android/scripts/widen_int64.py: the contract declares this
// field as a formatless integer, which generates as a 32-bit kotlin.Int
// and cannot hold its real range. Delete the patch once the server emits
// format: int64 — Int64WireContractTest says when.

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.AppVariant
import uz.bonvi.call.data.remote.dto.AudioMissingReason
import uz.bonvi.call.data.remote.dto.CallDirection
import uz.bonvi.call.data.remote.dto.CallDisposition
import uz.bonvi.call.data.remote.dto.CallSource
import uz.bonvi.call.data.remote.dto.CaptureRoute

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One call as the handset reports it.
 *
 * @param clientCallId UUIDv5 the device derives from call-log facts that survive a reinstall (SPEC §3.10). The idempotency key: a replay returns the same server id and creates no second row.
 * @param deviceEpochMs System.currentTimeMillis() at call start — raw evidence for skew.
 * @param deviceTimezone IANA name.
 * @param direction 
 * @param disposition 
 * @param startedAt ISO-8601 with an explicit offset (N36).
 * @param answeredAt 
 * @param appVariant 
 * @param appVersion 
 * @param audioExpected Whether the device will follow up with audio.
 * @param audioMissingReason 
 * @param captureRoute 
 * @param commandId 
 * @param contactName 
 * @param deviceRttMs 
 * @param durationSec Whole seconds, truncated not rounded.
 * @param endedAt 
 * @param reconciledWithCallLog 
 * @param remoteNumber 
 * @param ringSec 
 * @param simSlot 
 * @param simSubscriptionId 
 * @param source 
 */


data class DeviceCallIn (

    /* UUIDv5 the device derives from call-log facts that survive a reinstall (SPEC §3.10). The idempotency key: a replay returns the same server id and creates no second row. */
    @Json(name = "client_call_id")
    val clientCallId: java.util.UUID,

    /* System.currentTimeMillis() at call start — raw evidence for skew. */
    @Json(name = "device_epoch_ms")
    val deviceEpochMs: kotlin.Long,

    /* IANA name. */
    @Json(name = "device_timezone")
    val deviceTimezone: kotlin.String,

    @Json(name = "direction")
    val direction: CallDirection,

    @Json(name = "disposition")
    val disposition: CallDisposition,

    /* ISO-8601 with an explicit offset (N36). */
    @Json(name = "started_at")
    val startedAt: java.time.OffsetDateTime,

    @Json(name = "answered_at")
    val answeredAt: java.time.OffsetDateTime? = null,

    @Json(name = "app_variant")
    val appVariant: AppVariant? = null,

    @Json(name = "app_version")
    val appVersion: kotlin.String? = null,

    /* Whether the device will follow up with audio. */
    @Json(name = "audio_expected")
    val audioExpected: kotlin.Boolean? = false,

    @Json(name = "audio_missing_reason")
    val audioMissingReason: AudioMissingReason? = null,

    @Json(name = "capture_route")
    val captureRoute: CaptureRoute? = null,

    @Json(name = "command_id")
    val commandId: java.util.UUID? = null,

    @Json(name = "contact_name")
    val contactName: kotlin.String? = null,

    @Json(name = "device_rtt_ms")
    val deviceRttMs: kotlin.Int? = null,

    /* Whole seconds, truncated not rounded. */
    @Json(name = "duration_sec")
    val durationSec: kotlin.Int? = 0,

    @Json(name = "ended_at")
    val endedAt: java.time.OffsetDateTime? = null,

    @Json(name = "reconciled_with_call_log")
    val reconciledWithCallLog: kotlin.Boolean? = false,

    @Json(name = "remote_number")
    val remoteNumber: kotlin.String? = null,

    @Json(name = "ring_sec")
    val ringSec: kotlin.Int? = null,

    @Json(name = "sim_slot")
    val simSlot: kotlin.Int? = null,

    @Json(name = "sim_subscription_id")
    val simSubscriptionId: kotlin.Int? = null,

    @Json(name = "source")
    val source: CallSource? = null

) {


}

