/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.DeviceEventDetailIn

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``POST /api/device/v1/events`` — device events that are not calls.
 *
 * @param kind One of the names in SPEC §4.4. Unknown names are accepted on purpose — an event we do not understand raises 'info' rather than being dropped — but the shape is constrained to a lower-case identifier: an unbounded free-text field is itself a way off the phone.
 * @param at 
 * @param detail Named fields only; see DeviceEventDetailIn.
 */


data class DeviceEventIn (

    /* One of the names in SPEC §4.4. Unknown names are accepted on purpose — an event we do not understand raises 'info' rather than being dropped — but the shape is constrained to a lower-case identifier: an unbounded free-text field is itself a way off the phone. */
    @Json(name = "kind")
    val kind: kotlin.String,

    @Json(name = "at")
    val at: java.time.OffsetDateTime? = null,

    /* Named fields only; see DeviceEventDetailIn. */
    @Json(name = "detail")
    val detail: DeviceEventDetailIn? = null

) {


}

