/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.DeviceCommandOut

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param commands 
 * @param serverTime 
 */


data class DeviceCommandListOut (

    @Json(name = "commands")
    val commands: kotlin.collections.List<DeviceCommandOut>,

    @Json(name = "server_time")
    val serverTime: java.time.OffsetDateTime

) {


}

