/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.DeviceCallOut

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A page of the employee's own calls.  Same shape as the panel's list (``items``/``next_cursor``/``has_more``) so there is one pagination convention in the product. ``total`` is left unset: a phone scrolls, and a COUNT per page is cellular data spent on a number nobody reads.
 *
 * @param hasMore 
 * @param items 
 * @param nextCursor 
 * @param total 
 */


data class DeviceCallListOut (

    @Json(name = "has_more")
    val hasMore: kotlin.Boolean,

    @Json(name = "items")
    val items: kotlin.collections.List<DeviceCallOut>,

    @Json(name = "next_cursor")
    val nextCursor: kotlin.String?,

    @Json(name = "total")
    val total: kotlin.Int? = null

) {


}

