/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.EnrolmentOutcome
import uz.bonvi.call.data.remote.dto.InstallationStatus
import uz.bonvi.call.data.remote.dto.IssuedTokensOut
import uz.bonvi.call.data.remote.dto.VerificationState

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Polled every two seconds for at most five minutes.
 *
 * @param state 
 * @param failure 
 * @param status 
 * @param tokens 
 */


data class DeviceVerificationStatusOut (

    @Json(name = "state")
    val state: VerificationState,

    @Json(name = "failure")
    val failure: EnrolmentOutcome? = null,

    @Json(name = "status")
    val status: InstallationStatus? = null,

    @Json(name = "tokens")
    val tokens: IssuedTokensOut? = null

) {


}

