/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Alerts are raised inside this request, so the 10-minute bound of UC-06 is a device-reporting-interval question and not a server-latency one.
 *
 * @param accepted 
 * @param alertsRaised 
 * @param serverTime 
 * @param transitions 
 */


data class DeviceCapabilityBatchOut (

    @Json(name = "accepted")
    val accepted: kotlin.Int,

    @Json(name = "alerts_raised")
    val alertsRaised: kotlin.Int,

    @Json(name = "server_time")
    val serverTime: java.time.OffsetDateTime,

    @Json(name = "transitions")
    val transitions: kotlin.Int

) {


}

