/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accepted 
 * @param alertsRaised 
 * @param serverTime 
 */


data class DeviceEventBatchOut (

    @Json(name = "accepted")
    val accepted: kotlin.Int,

    @Json(name = "alerts_raised")
    val alertsRaised: kotlin.Int,

    @Json(name = "server_time")
    val serverTime: java.time.OffsetDateTime

) {


}

