/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The handset, as it describes itself. No raw hardware identifier.
 *
 * @param androidRelease 
 * @param apiLevel 
 * @param buildFingerprintHash sha256 of Build.FINGERPRINT.
 * @param manufacturer 
 * @param model 
 * @param marketingName 
 */


data class DeviceInfoIn (

    @Json(name = "android_release")
    val androidRelease: kotlin.String,

    @Json(name = "api_level")
    val apiLevel: kotlin.Int,

    /* sha256 of Build.FINGERPRINT. */
    @Json(name = "build_fingerprint_hash")
    val buildFingerprintHash: kotlin.String,

    @Json(name = "manufacturer")
    val manufacturer: kotlin.String,

    @Json(name = "model")
    val model: kotlin.String,

    @Json(name = "marketing_name")
    val marketingName: kotlin.String? = null

) {


}

