/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param delta 
 * @param deviceCounted 
 * @param periodDate 
 * @param serverTime 
 * @param uploadedCount 
 */


data class DeviceCallLogDeltaOut (

    @Json(name = "delta")
    val delta: kotlin.Int,

    @Json(name = "device_counted")
    val deviceCounted: kotlin.Int,

    @Json(name = "period_date")
    val periodDate: java.time.LocalDate,

    @Json(name = "server_time")
    val serverTime: java.time.OffsetDateTime,

    @Json(name = "uploaded_count")
    val uploadedCount: kotlin.Int

) {


}

