/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.InstallationStatus
import uz.bonvi.call.data.remote.dto.VerificationMethod

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Issued once the installation is verified.
 *
 * @param accessToken 
 * @param expiresIn 
 * @param installationId 
 * @param refreshToken 
 * @param serverTime 
 * @param status 
 * @param tokenType 
 * @param verificationMethod 
 */


data class DeviceTokenPairOut (

    @Json(name = "access_token")
    val accessToken: kotlin.String,

    @Json(name = "expires_in")
    val expiresIn: kotlin.Int,

    @Json(name = "installation_id")
    val installationId: java.util.UUID,

    @Json(name = "refresh_token")
    val refreshToken: kotlin.String,

    @Json(name = "server_time")
    val serverTime: java.time.OffsetDateTime,

    @Json(name = "status")
    val status: InstallationStatus,

    @Json(name = "token_type")
    val tokenType: kotlin.String? = "bearer",

    @Json(name = "verification_method")
    val verificationMethod: VerificationMethod? = null

) {


}

