/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``POST /api/device/v1/call-log-delta`` — the production rig (§4.1 B).  Without this, capture rate becomes unverifiable the day the acceptance window ends: there is no adb on a phone Bonvi does not own.
 *
 * @param deviceCounted Rows the device saw in its own log.
 * @param periodDate Asia/Tashkent calendar date.
 * @param uploadedCount 
 * @param subscriptionUnknownCount Calls the OS could not attribute to a subscription. Reported separately and never folded into either side of the rate — that is the fail-closed rule made visible.
 * @param sweptAt 
 */


data class DeviceCallLogDeltaIn (

    /* Rows the device saw in its own log. */
    @Json(name = "device_counted")
    val deviceCounted: kotlin.Int,

    /* Asia/Tashkent calendar date. */
    @Json(name = "period_date")
    val periodDate: java.time.LocalDate,

    @Json(name = "uploaded_count")
    val uploadedCount: kotlin.Int,

    /* Calls the OS could not attribute to a subscription. Reported separately and never folded into either side of the rate — that is the fail-closed rule made visible. */
    @Json(name = "subscription_unknown_count")
    val subscriptionUnknownCount: kotlin.Int? = 0,

    @Json(name = "swept_at")
    val sweptAt: java.time.OffsetDateTime? = null

) {


}

