/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.CommandFailureReason

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``POST /api/device/v1/commands/{id}/ack``.
 *
 * @param status 
 * @param at 
 * @param failureReason 
 * @param resultClientCallId The call the dial produced, if it produced one.
 */


data class DeviceAckIn (

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "at")
    val at: java.time.OffsetDateTime? = null,

    @Json(name = "failure_reason")
    val failureReason: CommandFailureReason? = null,

    /* The call the dial produced, if it produced one. */
    @Json(name = "result_client_call_id")
    val resultClientCallId: java.util.UUID? = null

) {


}

