/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.UpdateBlockOut

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``server_time`` lets the app compute skew without an extra round trip.
 *
 * @param clockSkewSec 
 * @param serverTime 
 * @param update 
 * @param configHash 
 * @param pendingCommandCount 
 */


data class DeviceHeartbeatOut (

    @Json(name = "clock_skew_sec")
    val clockSkewSec: kotlin.Int,

    @Json(name = "server_time")
    val serverTime: java.time.OffsetDateTime,

    @Json(name = "update")
    val update: UpdateBlockOut,

    @Json(name = "config_hash")
    val configHash: kotlin.String? = null,

    @Json(name = "pending_command_count")
    val pendingCommandCount: kotlin.Int? = 0

) {


}

