/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.AudioMissingReason
import uz.bonvi.call.data.remote.dto.CallDirection
import uz.bonvi.call.data.remote.dto.CallDisposition
import uz.bonvi.call.data.remote.dto.CaptureRoute
import uz.bonvi.call.data.remote.dto.DeviceAudioState

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One call, as the employee sees it in the app.  Every field here is also a field a lost handset carries, so the list is the client's request and nothing more: no note, no colleague, no search. It is the promise in ``docs/QOLLANMA.md`` becoming a screen — N41 one step further, from *which number is recorded* to *what was recorded*.
 *
 * @param audioMissingReason Why there is no recording, or null when there is one. Null is not the app's cue to say nothing — `audio_state` is what it renders.
 * @param audioState **Never null.** One value the app switches on to produce one Uzbek sentence. This screen is where an employee learns that *qayd etish* and *yozib olish* are different promises, so it must always have something to say.
 * @param clientCallId So the app can match the row it queued itself.
 * @param contactName 
 * @param direction 
 * @param disposition 
 * @param durationSec 
 * @param hasAudio What the **server holds**, never what the device believes it sent. A list built locally would show calls that never uploaded and hide calls recovered from the call log.
 * @param id Server id; the audio route takes this.
 * @param remoteNumber 
 * @param startedAt 
 * @param captureRoute Which strategy produced the recording. Null when there is none — the route is a property of the file, not of the call.
 */


data class DeviceCallOut (

    /* Why there is no recording, or null when there is one. Null is not the app's cue to say nothing — `audio_state` is what it renders. */
    @Json(name = "audio_missing_reason")
    val audioMissingReason: AudioMissingReason?,

    /* **Never null.** One value the app switches on to produce one Uzbek sentence. This screen is where an employee learns that *qayd etish* and *yozib olish* are different promises, so it must always have something to say. */
    @Json(name = "audio_state")
    val audioState: DeviceAudioState,

    /* So the app can match the row it queued itself. */
    @Json(name = "client_call_id")
    val clientCallId: java.util.UUID,

    @Json(name = "contact_name")
    val contactName: kotlin.String?,

    @Json(name = "direction")
    val direction: CallDirection,

    @Json(name = "disposition")
    val disposition: CallDisposition,

    @Json(name = "duration_sec")
    val durationSec: kotlin.Int,

    /* What the **server holds**, never what the device believes it sent. A list built locally would show calls that never uploaded and hide calls recovered from the call log. */
    @Json(name = "has_audio")
    val hasAudio: kotlin.Boolean,

    /* Server id; the audio route takes this. */
    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "remote_number")
    val remoteNumber: kotlin.String?,

    @Json(name = "started_at")
    val startedAt: java.time.OffsetDateTime,

    /* Which strategy produced the recording. Null when there is none — the route is a property of the file, not of the call. */
    @Json(name = "capture_route")
    val captureRoute: CaptureRoute? = null

) {


}

