/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.DeviceCallResultOut

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``200`` for the batch, whatever happened to the individual items.
 *
 * @param results 
 * @param serverTime So the app can compute skew without an extra round trip.
 */


data class DeviceCallBatchOut (

    @Json(name = "results")
    val results: kotlin.collections.List<DeviceCallResultOut>,

    /* So the app can compute skew without an extra round trip. */
    @Json(name = "server_time")
    val serverTime: java.time.OffsetDateTime

) {


}

