/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``POST /api/device/v1/auth/refresh``.
 *
 * @param refreshToken 
 */


data class DeviceRefreshIn (

    @Json(name = "refresh_token")
    val refreshToken: kotlin.String

) {


}

