/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``POST /api/device/v1/enrolment/verify/msisdn`` — route 1.
 *
 * @param carrierName 
 * @param line1Number TelephonyManager.getLine1Number(). NULL, empty or fewer than nine digits is never a match (UC-04) — it is 'I don't know', not 'yes'.
 * @param simSlot 
 * @param subscriptionId 
 */


data class DeviceMsisdnVerifyIn (

    @Json(name = "carrier_name")
    val carrierName: kotlin.String? = null,

    /* TelephonyManager.getLine1Number(). NULL, empty or fewer than nine digits is never a match (UC-04) — it is 'I don't know', not 'yes'. */
    @Json(name = "line1_number")
    val line1Number: kotlin.String? = null,

    @Json(name = "sim_slot")
    val simSlot: kotlin.Int? = null,

    @Json(name = "subscription_id")
    val subscriptionId: kotlin.Int? = null

) {


}

