/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.DeviceCapabilityIn

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``POST /api/device/v1/capabilities``.
 *
 * @param capabilities 
 */


data class DeviceCapabilityBatchIn (

    @Json(name = "capabilities")
    val capabilities: kotlin.collections.List<DeviceCapabilityIn>

) {


}

