/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

// PATCHED by android/scripts/widen_int64.py: the contract declares this
// field as a formatless integer, which generates as a 32-bit kotlin.Int
// and cannot hold its real range. Delete the patch once the server emits
// format: int64 — Int64WireContractTest says when.

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.AppVariant
import uz.bonvi.call.data.remote.dto.CaptureRoute
import uz.bonvi.call.data.remote.dto.NetworkType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``POST /api/device/v1/heartbeat`` — every 120 s while the service lives.
 *
 * @param deviceEpochMs Raw device clock; the skew evidence (N36).
 * @param deviceTimezone 
 * @param apiLevel 
 * @param appVariant 
 * @param appVersion 
 * @param batteryCharging 
 * @param batteryLevel 
 * @param batteryOptimisationExempt 
 * @param captureEnabled 
 * @param cellularBytesMonth 
 * @param deviceRttMs 
 * @param freeStorageBytes 
 * @param networkType 
 * @param parkedRecords 
 * @param pendingCommandsSeen 
 * @param powerSaveMode 
 * @param queueBytes 
 * @param queueOldestAt 
 * @param queueRecords 
 * @param recordingRoute 
 * @param recordingRouteOk 
 * @param serviceRunning 
 * @param wsConnected 
 */


data class DeviceHeartbeatIn (

    /* Raw device clock; the skew evidence (N36). */
    @Json(name = "device_epoch_ms")
    val deviceEpochMs: kotlin.Long,

    @Json(name = "device_timezone")
    val deviceTimezone: kotlin.String,

    @Json(name = "api_level")
    val apiLevel: kotlin.Int? = null,

    @Json(name = "app_variant")
    val appVariant: AppVariant? = null,

    @Json(name = "app_version")
    val appVersion: kotlin.String? = null,

    @Json(name = "battery_charging")
    val batteryCharging: kotlin.Boolean? = null,

    @Json(name = "battery_level")
    val batteryLevel: kotlin.Int? = null,

    @Json(name = "battery_optimisation_exempt")
    val batteryOptimisationExempt: kotlin.Boolean? = null,

    @Json(name = "capture_enabled")
    val captureEnabled: kotlin.Boolean? = null,

    @Json(name = "cellular_bytes_month")
    val cellularBytesMonth: kotlin.Long? = null,

    @Json(name = "device_rtt_ms")
    val deviceRttMs: kotlin.Int? = null,

    @Json(name = "free_storage_bytes")
    val freeStorageBytes: kotlin.Long? = null,

    @Json(name = "network_type")
    val networkType: NetworkType? = null,

    @Json(name = "parked_records")
    val parkedRecords: kotlin.Int? = null,

    @Json(name = "pending_commands_seen")
    val pendingCommandsSeen: kotlin.Int? = null,

    @Json(name = "power_save_mode")
    val powerSaveMode: kotlin.Boolean? = null,

    @Json(name = "queue_bytes")
    val queueBytes: kotlin.Long? = null,

    @Json(name = "queue_oldest_at")
    val queueOldestAt: java.time.OffsetDateTime? = null,

    @Json(name = "queue_records")
    val queueRecords: kotlin.Int? = null,

    @Json(name = "recording_route")
    val recordingRoute: CaptureRoute? = null,

    @Json(name = "recording_route_ok")
    val recordingRouteOk: kotlin.Boolean? = null,

    @Json(name = "service_running")
    val serviceRunning: kotlin.Boolean? = null,

    @Json(name = "ws_connected")
    val wsConnected: kotlin.Boolean? = null

) {


}

