/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Every way an enrolment step can end. The funnel's evidence base.
 *
 * Values: OK,CODE_NOT_FOUND,CODE_ALREADY_USED,CODE_EXPIRED,CODE_REVOKED,NUMBER_MISMATCH,MSISDN_EMPTY,NO_CALLER_ID,TIMEOUT,RECEIVER_DOWN,ALREADY_BOUND,REJECTED
 */

@JsonClass(generateAdapter = false)
enum class EnrolmentOutcome(val value: kotlin.String) {

    @Json(name = "ok")
    OK("ok"),

    @Json(name = "code_not_found")
    CODE_NOT_FOUND("code_not_found"),

    @Json(name = "code_already_used")
    CODE_ALREADY_USED("code_already_used"),

    @Json(name = "code_expired")
    CODE_EXPIRED("code_expired"),

    @Json(name = "code_revoked")
    CODE_REVOKED("code_revoked"),

    @Json(name = "number_mismatch")
    NUMBER_MISMATCH("number_mismatch"),

    @Json(name = "msisdn_empty")
    MSISDN_EMPTY("msisdn_empty"),

    @Json(name = "no_caller_id")
    NO_CALLER_ID("no_caller_id"),

    @Json(name = "timeout")
    TIMEOUT("timeout"),

    @Json(name = "receiver_down")
    RECEIVER_DOWN("receiver_down"),

    @Json(name = "already_bound")
    ALREADY_BOUND("already_bound"),

    @Json(name = "rejected")
    REJECTED("rejected");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EnrolmentOutcome) "$data" else null

        /**
         * Returns a valid [EnrolmentOutcome] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EnrolmentOutcome? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

