/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The body of every non-2xx answer (N35, SPEC §4.0).  A model rather than a fragment hand-written in the exporter, so the shape clients generate against is the shape ``main.error_envelope`` builds. ``tests/test_conformance.py`` drives real requests through both.
 *
 * @param code The stable machine value. Clients branch on this.
 * @param message Uzbek, for a person. Never branched on (§4.0).
 * @param requestId Echoed from X-Request-Id; quote it in a bug report.
 * @param detail 
 */


data class ErrorBody (

    /* The stable machine value. Clients branch on this. */
    @Json(name = "code")
    val code: kotlin.String,

    /* Uzbek, for a person. Never branched on (§4.0). */
    @Json(name = "message")
    val message: kotlin.String,

    /* Echoed from X-Request-Id; quote it in a bug report. */
    @Json(name = "request_id")
    val requestId: kotlin.String,

    @Json(name = "detail")
    val detail: kotlin.Any? = null

) {


}

