/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Lifecycle of one app installation bound to one registered number.
 *
 * Values: PENDING,ACTIVE,REPLACED,REVOKED,REVOKED_PENDING_CONFIRMATION
 */

@JsonClass(generateAdapter = false)
enum class InstallationStatus(val value: kotlin.String) {

    @Json(name = "pending")
    PENDING("pending"),

    @Json(name = "active")
    ACTIVE("active"),

    @Json(name = "replaced")
    REPLACED("replaced"),

    @Json(name = "revoked")
    REVOKED("revoked"),

    @Json(name = "revoked_pending_confirmation")
    REVOKED_PENDING_CONFIRMATION("revoked_pending_confirmation");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is InstallationStatus) "$data" else null

        /**
         * Returns a valid [InstallationStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): InstallationStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

