/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The pair handed over once verification succeeds.  Named rather than a map because the generated Kotlin DTO is what the app reads: a ``Map<String, Any>`` there makes a renamed field a runtime ``null`` on a fleet we cannot force-update, which is exactly what CONVENTIONS.md §1 generates clients to prevent.
 *
 * @param accessToken 
 * @param expiresIn 
 * @param refreshToken 
 * @param tokenType 
 */


data class IssuedTokensOut (

    @Json(name = "access_token")
    val accessToken: kotlin.String,

    @Json(name = "expires_in")
    val expiresIn: kotlin.Int,

    @Json(name = "refresh_token")
    val refreshToken: kotlin.String,

    @Json(name = "token_type")
    val tokenType: kotlin.String? = "bearer"

) {


}

