/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.AudioCodec
import uz.bonvi.call.data.remote.dto.AudioContainer
import uz.bonvi.call.data.remote.dto.CaptureRoute

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``POST /calls/{client_call_id}/audio/session`` — step 1 of three.
 *
 * @param bytesTotal Declared file size.
 * @param captureRoute 
 * @param codec 
 * @param container 
 * @param recordedAt When the file was written. Checked against the call's window — a recording that does not overlap is refused and never stored (N28).
 * @param sha256 
 * @param bitrateBps 
 * @param captureRouteDetail 
 * @param channels 
 * @param durationMs 
 * @param sampleRateHz 
 */


data class OpenUploadIn (

    /* Declared file size. */
    @Json(name = "bytes_total")
    val bytesTotal: kotlin.Int,

    @Json(name = "capture_route")
    val captureRoute: CaptureRoute,

    @Json(name = "codec")
    val codec: AudioCodec,

    @Json(name = "container")
    val container: AudioContainer,

    /* When the file was written. Checked against the call's window — a recording that does not overlap is refused and never stored (N28). */
    @Json(name = "recorded_at")
    val recordedAt: java.time.OffsetDateTime,

    @Json(name = "sha256")
    val sha256: kotlin.String,

    @Json(name = "bitrate_bps")
    val bitrateBps: kotlin.Int? = null,

    @Json(name = "capture_route_detail")
    val captureRouteDetail: kotlin.String? = null,

    @Json(name = "channels")
    val channels: kotlin.Int? = null,

    @Json(name = "duration_ms")
    val durationMs: kotlin.Int? = null,

    @Json(name = "sample_rate_hz")
    val sampleRateHz: kotlin.Int? = null

) {


}

