/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``201``, or the **existing** open session — that is the resume path.
 *
 * @param chunkSize The client always obeys this value.
 * @param expiresAt 
 * @param receivedBytes Resume from here. After an app restart this is not zero.
 * @param uploadId 
 */


data class OpenUploadOut (

    /* The client always obeys this value. */
    @Json(name = "chunk_size")
    val chunkSize: kotlin.Int,

    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime,

    /* Resume from here. After an app restart this is not zero. */
    @Json(name = "received_bytes")
    val receivedBytes: kotlin.Int,

    @Json(name = "upload_id")
    val uploadId: java.util.UUID

) {


}

