/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.ReceiverStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * What the app needs to run screen E5.
 *
 * @param required 
 * @param windowSeconds 
 * @param callbackMsisdn NULL when no receiver is available.
 * @param receiverStatus 
 */


data class RedeemVerificationOut (

    @Json(name = "required")
    val required: kotlin.Boolean,

    @Json(name = "window_seconds")
    val windowSeconds: kotlin.Int,

    /* NULL when no receiver is available. */
    @Json(name = "callback_msisdn")
    val callbackMsisdn: kotlin.String? = null,

    @Json(name = "receiver_status")
    val receiverStatus: ReceiverStatus? = null

) {


}

