/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param display Grouped for reading aloud, e.g. +998 90 111-22-33.
 * @param e164 
 */


data class RedeemNumberOut (

    /* Grouped for reading aloud, e.g. +998 90 111-22-33. */
    @Json(name = "display")
    val display: kotlin.String,

    @Json(name = "e164")
    val e164: kotlin.String

) {


}

