/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Carried on every device response (SPEC §4.3).  The app keeps capturing and draining while ``required`` is true; it blocks only new enrolment actions. Refusing an old version must never destroy data.
 *
 * @param minVersionCode 
 * @param required 
 * @param apkUrl 
 * @param latestVersion 
 * @param latestVersionCode 
 * @param messageUz 
 */


data class UpdateBlockOut (

    @Json(name = "min_version_code")
    val minVersionCode: kotlin.Int,

    @Json(name = "required")
    val required: kotlin.Boolean,

    @Json(name = "apk_url")
    val apkUrl: kotlin.String? = null,

    @Json(name = "latest_version")
    val latestVersion: kotlin.String? = null,

    @Json(name = "latest_version_code")
    val latestVersionCode: kotlin.Int? = null,

    @Json(name = "message_uz")
    val messageUz: kotlin.String? = null

) {


}

