/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto

import uz.bonvi.call.data.remote.dto.UploadStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ``GET /audio/{upload_id}`` — the probe (step 4).
 *
 * @param bytesTotal 
 * @param expiresAt 
 * @param receivedBytes 
 * @param status 
 * @param uploadId 
 */


data class UploadStatusOut (

    @Json(name = "bytes_total")
    val bytesTotal: kotlin.Int,

    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime,

    @Json(name = "received_bytes")
    val receivedBytes: kotlin.Int,

    @Json(name = "status")
    val status: UploadStatus,

    @Json(name = "upload_id")
    val uploadId: java.util.UUID

) {


}

