/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Resumable audio upload session state (SPEC §4.5).
 *
 * Values: OPEN,COMMITTED,EXPIRED,ABORTED
 */

@JsonClass(generateAdapter = false)
enum class UploadStatus(val value: kotlin.String) {

    @Json(name = "open")
    OPEN("open"),

    @Json(name = "committed")
    COMMITTED("committed"),

    @Json(name = "expired")
    EXPIRED("expired"),

    @Json(name = "aborted")
    ABORTED("aborted");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is UploadStatus) "$data" else null

        /**
         * Returns a valid [UploadStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): UploadStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

