/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * How we proved the phone holds the registered number (UC-04, T142).  Ordered strongest to weakest, and the order is load-bearing: SPEC §9.3 requires the identity anchor to degrade visibly, so every place that renders a binding renders which of these it rests on.  ``self_declared`` is the weakest. It says only that whoever held the single-use code an admin issued for this number typed it into this handset — no line was proven. It exists because on this fleet the two proving routes are frequently both unavailable: Uzbek SIMs leave ``getLine1Number()`` empty, and the callback route needs a receiver line. Without it those handsets have no path to ``active`` at all, which is strictly worse: an unenrolled phone reports nothing, so nobody can even see that it is unverified. Governed by ``enrolment.allow_self_declared``.
 *
 * Values: SIM_MSISDN,CALLBACK,ADMIN_ATTESTED,SELF_DECLARED
 */

@JsonClass(generateAdapter = false)
enum class VerificationMethod(val value: kotlin.String) {

    @Json(name = "sim_msisdn")
    SIM_MSISDN("sim_msisdn"),

    @Json(name = "callback")
    CALLBACK("callback"),

    @Json(name = "admin_attested")
    ADMIN_ATTESTED("admin_attested"),

    @Json(name = "self_declared")
    SELF_DECLARED("self_declared");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is VerificationMethod) "$data" else null

        /**
         * Returns a valid [VerificationMethod] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): VerificationMethod? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

