/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * How we proved the phone holds the registered number (UC-04, T142).
 *
 * Values: SIM_MSISDN,CALLBACK,ADMIN_ATTESTED
 */

@JsonClass(generateAdapter = false)
enum class VerificationMethod(val value: kotlin.String) {

    @Json(name = "sim_msisdn")
    SIM_MSISDN("sim_msisdn"),

    @Json(name = "callback")
    CALLBACK("callback"),

    @Json(name = "admin_attested")
    ADMIN_ATTESTED("admin_attested");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is VerificationMethod) "$data" else null

        /**
         * Returns a valid [VerificationMethod] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): VerificationMethod? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

