/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package uz.bonvi.call.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * State of one verification attempt.
 *
 * Values: PENDING,MATCHED,FAILED,EXPIRED,ATTESTED,SELF_DECLARED
 */

@JsonClass(generateAdapter = false)
enum class VerificationState(val value: kotlin.String) {

    @Json(name = "pending")
    PENDING("pending"),

    @Json(name = "matched")
    MATCHED("matched"),

    @Json(name = "failed")
    FAILED("failed"),

    @Json(name = "expired")
    EXPIRED("expired"),

    @Json(name = "attested")
    ATTESTED("attested"),

    @Json(name = "self_declared")
    SELF_DECLARED("self_declared");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is VerificationState) "$data" else null

        /**
         * Returns a valid [VerificationState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): VerificationState? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

