"""Create the release-1 schema.

The whole of SPEC §3 in **one** revision: 30 tables, 30 native enums, the
generated last-9 key columns, the constraints that are the product, and the
seeded settings. Every later change is its own revision; no task in Phases 3-5
adds a migration (CONVENTIONS.md §10, TASKS.md T19/T146/T147).

There is no ``bootstrap.py``, no ``create_all`` and no ``COLUMN_PATCHES``.
BonviZvonki's schema comes from ``create_all`` plus a list of
``ALTER TABLE ... IF NOT EXISTS`` strings, which works exactly as long as every
change is "add a nullable column": it cannot express a rename, a type change, a
backfill, a constraint or a rollback, and ``create_all`` silently ignores
existing tables so dev and prod diverge with no way to prove they match.

Four things in here are load-bearing and are the reason this file is partly
hand-written rather than wholly autogenerated:

* **``btree_gist`` is created before the exclusion constraint.** Without the
  extension the ``EXCLUDE USING gist`` silently fails to create — and that
  constraint is the only thing stopping two admins assigning one number to two
  agents at the same instant, which forks the identity anchor the whole product
  hangs on.
* **The generated last-9 key columns come from ``core.phone.phone_key_sql``.**
  The expressions below were produced by that function (CONVENTIONS.md §7); if
  the SQL and the Python ever disagree, every join on the key returns nothing —
  no error, no clue.
* **The four ``calls`` CHECK constraints.** They make the invalid states
  unrepresentable rather than merely untested: audio-less without a reason (N5),
  ``incoming`` + ``no_answer`` (UC-11), ``answered`` without ``answered_at`` and
  ``answered`` with ``duration_sec = 0`` (UC-09). The fourth one carries both
  duration rules of SPEC §3.5 in a single constraint.
* **The ``audit_log`` immutability trigger.** Append-only enforced by the
  database, not by convention: there is no route that updates or deletes an
  audit row, and now no code path — or psql session — can either (N27).

Every ``settings`` key of SPEC §3.8 is seeded here with its documented default,
so a missing key is a bug and not a silent ``None``. ``description_uz`` is left
NULL on purpose: Uzbek text in a ``.py`` file is legal only in
``core/messages_uz.py`` (CONVENTIONS.md §14), so the descriptions are the
settings module's to supply.

**This revision is the pre-release baseline and may still be edited in place.**
It has never run anywhere that matters — only on development machines — so a
follow-up revision reading "add two values to an enum that shipped an hour ago,
in a release that has not shipped at all" would be noise in a history people
read. **That licence ends at the first deploy to the real server (W03).** From
that moment 001 is frozen and every change is its own revision, without
exception. The rule and its trigger point are in ``docs/ASSUMPTIONS.md``.

Revision ID: 001
Revises:
Create Date: 2026-09-04
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Extensions the schema needs. ``pgcrypto`` is deliberately absent: hashing is
#: done in Python, where it can be tested without a database.
EXTENSIONS: tuple[str, ...] = ("btree_gist", "citext")

#: Every native enum, with its values in declaration order. Written out rather
#: than imported from ``core.enums`` because a migration must keep meaning even
#: after the application's enums have moved on; ``core/enums.py`` and this table
#: are compared by a test.
PG_ENUMS: dict[str, tuple[str, ...]] = {
    "user_role": ("admin", "manager", "sales",),
    "call_direction": ("incoming", "outgoing",),
    "call_disposition": ("answered", "missed", "rejected", "no_answer",),
    "call_type": ("internal", "external", "unknown",),
    "call_source": ("live_capture", "call_log_recovery",),
    "audio_missing_reason": (
        "pending_upload", "not_expected", "recording_route_unavailable", "oem_recorder_off",
        "no_permission", "capture_returned_silence", "app_not_running", "upload_expired",
        "queue_space_exhausted", "attribution_failed",
    ),
    "capture_route": (
        "oem_file_harvest", "app_voice_recognition", "app_voice_communication", "app_mic",
        "none",
    ),
    "audio_codec": ("opus", "aac_lc",),
    "audio_container": ("ogg", "mp4",),
    "app_variant": ("legacy28", "modern34",),
    "installation_status": (
        "pending", "active", "replaced", "revoked", "revoked_pending_confirmation",
    ),
    "verification_method": ("sim_msisdn", "callback", "admin_attested",),
    "verification_state": ("pending", "matched", "failed", "expired", "attested",),
    "funnel_stage": (
        "invited", "installed", "permitted", "number_verified", "verified_by_admin",
        "capturing", "needs_assisted_install", "install_disappeared", "revoked",
    ),
    "capability": (
        "phone_state", "call_log", "microphone", "contacts", "notifications", "call_phone",
        "battery_exemption", "storage_access", "oem_autostart", "foreground_service",
        "oem_recorder", "subscription_resolution",
    ),
    "capability_state": (
        "granted_working", "granted_not_working", "denied", "denied_permanently",
        "not_applicable", "unknown",
    ),
    "command_kind": ("dial", "config", "logout", "ping", "recheck",),
    "command_status": ("pending", "sent", "acknowledged", "failed", "expired",),
    "command_failure_reason": (
        "device_offline", "no_permission", "os_refused", "ack_timeout", "discarded_stale",
        "unsupported", "busy",
    ),
    "alert_kind": (
        "capture_disabled", "permission_lost_microphone", "permission_lost_phone_state",
        "permission_lost_call_log", "battery_optimisation_reenabled", "app_force_stopped",
        "install_disappeared", "recording_route_lost", "service_not_running", "device_offline",
        "device_silent", "fleet_silent", "capture_rate_regression", "queue_full",
        "storage_low", "poisoned_record", "auth_expired", "credential_replay",
        "installation_rebound", "callback_receiver_down", "enrolment_stalled",
        "attribution_out_of_range", "attribution_discarded_spike", "retention_job_failed",
        "backup_failed", "storage_capacity_low", "min_version_refusals",
    ),
    "alert_severity": ("info", "warning", "critical",),
    "actor_type": ("user", "service", "device", "system",),
    "audit_action": (
        "login_succeeded", "login_failed", "logout", "password_changed", "password_reset",
        "user_created", "user_updated", "user_deactivated", "agent_created", "agent_updated",
        "agent_archived", "agents_imported", "number_created", "number_updated",
        "assignment_created", "assignment_closed", "calls_reattributed",
        "enrolment_code_issued", "enrolment_code_revoked", "installation_attested",
        "installation_revoked", "installation_rebound", "command_issued",
        "call_note_updated", "calls_exported", "audio_play", "audio_download",
        "audio_deleted", "alert_acknowledged", "setting_updated", "retention_changed",
        "line_directory_updated", "supported_model_updated", "app_version_published",
        "service_token_created", "service_token_revoked", "export_read",
    ),
    "directory_rule_kind": ("exact", "prefix", "suffix",),
    "receiver_kind": ("gsm_gateway", "android_receiver",),
    "receiver_status": ("up", "degraded", "down",),
    "upload_status": ("open", "committed", "expired", "aborted",),
    "network_type": ("wifi", "cellular", "none",),
    "enrolment_attempt_kind": (
        "code_redeem", "msisdn_check", "callback_start", "callback_match", "admin_attest",
        "step_timing",
    ),
    "enrolment_outcome": (
        "ok", "code_not_found", "code_already_used", "code_expired", "code_revoked",
        "number_mismatch", "msisdn_empty", "no_caller_id", "timeout", "receiver_down",
        "already_bound", "rejected",
    ),
}


#: The circular foreign keys. Each pair records the match the other side made,
#: so neither table can be created after the other; the constraints are added
#: once both exist.
DEFERRED_FOREIGN_KEYS: tuple[tuple[str, str, str, str], ...] = (
    ("fk_calls_command", "calls", "commands", "command_id"),
    ("fk_enrolment_codes_installation", "enrolment_codes", "installations",
     "redeemed_by_installation_id"),
    ("fk_number_verifications_matched_event", "number_verifications", "callback_events",
     "matched_event_id"),
    ("fk_callback_events_matched_verification", "callback_events", "number_verifications",
     "matched_verification_id"),
)


#: SPEC §3.8. Nothing in the product hard-codes any of these: a threshold that
#: is not a row here is a threshold nobody can change without a deploy.
SETTINGS_SEED: tuple[tuple[str, object, str], ...] = (
    ("retention.audio_months", 12, "int"),
    ("retention.confirm_below_months", 3, "int"),
    ("retention.callback_events_days", 90, "int"),
    ("alerts.device_offline_minutes", 10, "int"),
    ("alerts.silence_hours", 4, "int"),
    ("alerts.fleet_silence_hours", 2, "int"),
    ("alerts.capture_regression_pp", 10, "int"),
    ("alerts.email_to", [], "list"),
    ("app.min_supported_version_code", 1, "int"),
    ("upload.chunk_size_bytes", 524288, "int"),
    ("upload.session_ttl_days", 7, "int"),
    ("upload.max_chunk_bytes", 4194304, "int"),
    ("data.cellular_cap_bytes_month", 1073741824, "int"),
    ("data.deferred_daily_cap_bytes", 5242880, "int"),
    ("audio.defer_to_wifi_hours", 24, "int"),
    ("queue.max_records", 2000, "int"),
    ("queue.max_audio_bytes", 1073741824, "int"),
    ("queue.min_free_space_bytes", 1073741824, "int"),
    ("device.heartbeat_seconds", 120, "int"),
    ("device.capability_recheck_hours", 6, "int"),
    ("device.call_log_sweep_hours", 6, "int"),
    ("working_hours.start", "08:00", "time"),
    ("working_hours.end", "20:00", "time"),
    ("working_hours.timezone", "Asia/Tashkent", "string"),
    # Mon-Sat. An assumption, recorded in docs/ASSUMPTIONS.md: Uzbek sales
    # weeks usually include Saturday. Correcting it is a settings change.
    ("working_hours.workdays", [1, 2, 3, 4, 5, 6], "list"),
    ("working_hours.holidays", [], "list"),
    ("enrolment.code_ttl_hours", 24, "int"),
    ("enrolment.callback_window_seconds", 300, "int"),
)

_settings_table = sa.table(
    "app_settings",
    sa.column("key", sa.String),
    sa.column("value", postgresql.JSONB),
    sa.column("value_type", sa.String),
)


def _enum(type_name: str) -> sa.Enum:
    return sa.Enum(*PG_ENUMS[type_name], name=type_name)


def upgrade() -> None:
    _create_extensions()
    for type_name in PG_ENUMS:
        _enum(type_name).create(op.get_bind(), checkfirst=False)

    op.create_table('agents',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('color', sa.String(length=16), server_default='#6366f1', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index('ix_agents_active', 'agents', ['is_active', 'full_name'], unique=False)
    op.create_index(op.f('ix_agents_full_name'), 'agents', ['full_name'], unique=False)
    op.create_index('uq_agents_employee_code', 'agents', ['employee_code'], unique=True, postgresql_where=sa.text('employee_code IS NOT NULL'))
    op.create_table('callback_receivers',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('msisdn', sa.String(length=20), nullable=False),
    sa.Column('kind', postgresql.ENUM('gsm_gateway', 'android_receiver', name='receiver_kind', create_type=False), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('up', 'degraded', 'down', name='receiver_status', create_type=False), server_default='down', nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callback_receivers'))
    )
    op.create_table('devices',
    sa.Column('manufacturer', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('marketing_name', sa.String(length=96), nullable=True),
    sa.Column('android_release', sa.String(length=16), nullable=False),
    sa.Column('api_level', sa.Integer(), nullable=False),
    sa.Column('build_fingerprint_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('build_fingerprint_hash', name=op.f('uq_devices_build_fingerprint_hash'))
    )
    op.create_index('ix_devices_model', 'devices', ['manufacturer', 'model', 'api_level'], unique=False)
    op.create_table('model_capture_stats',
    sa.Column('manufacturer', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('api_level', sa.Integer(), nullable=False),
    sa.Column('app_variant', postgresql.ENUM('legacy28', 'modern34', name='app_variant', create_type=False), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('answered_calls', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('calls_with_audio', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('baseline_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('delta_pp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('alert_raised', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_capture_stats')),
    sa.UniqueConstraint('manufacturer', 'model', 'api_level', 'app_variant', 'window_end', name='uq_model_capture_stats_window')
    )
    op.create_table('registered_numbers',
    sa.Column('e164', sa.String(length=20), nullable=False),
    sa.Column('phone_key', sa.CHAR(length=9), sa.Computed("CASE WHEN (length(regexp_replace(e164, '[^0-9]', '', 'g')) >= 9) THEN right(regexp_replace(e164, '[^0-9]', '', 'g'), 9) END", persisted=True), nullable=False),
    sa.Column('operator', sa.String(length=32), nullable=True),
    sa.Column('sim_owner', sa.String(length=16), server_default='company', nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sim_owner IN ('company', 'employee')", name=op.f('ck_registered_numbers_sim_owner_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registered_numbers')),
    sa.UniqueConstraint('phone_key', name='uq_registered_numbers_phone_key')
    )
    op.create_index('ix_registered_numbers_active', 'registered_numbers', ['is_active', 'e164'], unique=False)
    op.create_table('storage_usage_daily',
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('audio_bytes_total', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('audio_files', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes_added', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes_deleted', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('period_date', name=op.f('pk_storage_usage_daily'))
    )
    op.create_table('supported_models',
    sa.Column('manufacturer', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('api_level', sa.Integer(), nullable=False),
    sa.Column('app_variant', postgresql.ENUM('legacy28', 'modern34', name='app_variant', create_type=False), nullable=False),
    sa.Column('capture_route', postgresql.ENUM('oem_file_harvest', 'app_voice_recognition', 'app_voice_communication', 'app_mic', 'none', name='capture_route', create_type=False), nullable=False),
    sa.Column('baseline_audio_capture_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('baseline_sample_calls', sa.Integer(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_supported', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('callback_verification_ok', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supported_models')),
    sa.UniqueConstraint('manufacturer', 'model', 'api_level', 'app_variant', name='uq_supported_models_identity')
    )
    op.create_table('callback_events',
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('caller_e164', sa.String(length=20), nullable=True),
    sa.Column('caller_key', sa.CHAR(length=9), sa.Computed("CASE WHEN (length(regexp_replace(caller_e164, '[^0-9]', '', 'g')) >= 9) THEN right(regexp_replace(caller_e164, '[^0-9]', '', 'g'), 9) END", persisted=True), nullable=True),
    sa.Column('cli_presented', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('receiver_epoch_ms', sa.BigInteger(), nullable=True),
    sa.Column('matched_verification_id', sa.UUID(), nullable=True),
    sa.Column('unmatched_reason', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['callback_receivers.id'], name=op.f('fk_callback_events_receiver_id_callback_receivers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callback_events'))
    )
    op.create_index('ix_callback_events_caller', 'callback_events', ['caller_key', sa.text('received_at DESC')], unique=False)
    op.create_index('ix_callback_events_receiver', 'callback_events', ['receiver_id', sa.text('received_at DESC')], unique=False)
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'manager', 'sales', 'viewer', name='user_role', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role <> 'sales' OR agent_id IS NOT NULL", name=op.f('ck_users_sales_user_requires_agent')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_users_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_active_admin', 'users', ['role'], unique=False, postgresql_where=sa.text("is_active AND role = 'admin'"))
    op.create_index('ix_users_agent_id', 'users', ['agent_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('description_uz', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_app_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('app_versions',
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('version_code', sa.Integer(), nullable=False),
    sa.Column('variant', postgresql.ENUM('legacy28', 'modern34', name='app_variant', create_type=False), nullable=False),
    sa.Column('apk_path', sa.Text(), nullable=False),
    sa.Column('apk_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('min_api_level', sa.Integer(), server_default=sa.text('26'), nullable=False),
    sa.Column('release_notes_uz', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_app_versions_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_versions')),
    sa.UniqueConstraint('variant', 'version_code', name='uq_app_versions_variant_code')
    )
    op.create_index('uq_app_versions_current', 'app_versions', ['variant'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('enrolment_codes',
    sa.Column('code', sa.CHAR(length=8), nullable=False),
    sa.Column('number_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('issued_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by_installation_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_enrolment_codes_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], name=op.f('fk_enrolment_codes_issued_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['number_id'], ['registered_numbers.id'], name=op.f('fk_enrolment_codes_number_id_registered_numbers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], name=op.f('fk_enrolment_codes_revoked_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrolment_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_enrolment_codes_code'))
    )
    op.create_index('ix_codes_number_active', 'enrolment_codes', ['number_id'], unique=False, postgresql_where=sa.text('redeemed_at IS NULL AND revoked_at IS NULL'))
    op.create_table('installations',
    sa.Column('number_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'active', 'replaced', 'revoked', 'revoked_pending_confirmation', name='installation_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('verification_method', postgresql.ENUM('sim_msisdn', 'callback', 'admin_attested', name='verification_method', create_type=False), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attested_by', sa.UUID(), nullable=True),
    sa.Column('attest_reason', sa.String(length=255), nullable=True),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_pending_records', sa.Integer(), nullable=True),
    sa.Column('revoke_pending_bytes', sa.BigInteger(), nullable=True),
    sa.Column('credential_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('device_fingerprint_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('refresh_token_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('app_variant', postgresql.ENUM('legacy28', 'modern34', name='app_variant', create_type=False), nullable=True),
    sa.Column('sim_subscription_id', sa.Integer(), nullable=True),
    sa.Column('sim_slot', sa.SmallInteger(), nullable=True),
    sa.Column('funnel_stage', postgresql.ENUM('invited', 'installed', 'permitted', 'number_verified', 'verified_by_admin', 'capturing', 'needs_assisted_install', 'install_disappeared', 'revoked', name='funnel_stage', create_type=False), server_default='invited', nullable=False),
    sa.Column('funnel_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_method <> 'admin_attested' OR attest_reason IS NOT NULL", name=op.f('ck_installations_attestation_needs_reason')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_installations_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['attested_by'], ['users.id'], name=op.f('fk_installations_attested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_installations_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['number_id'], ['registered_numbers.id'], name=op.f('fk_installations_number_id_registered_numbers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installations'))
    )
    op.create_index('ix_installations_agent', 'installations', ['agent_id', 'status'], unique=False)
    op.create_index('ix_installations_stage', 'installations', ['funnel_stage', sa.text('funnel_changed_at DESC')], unique=False)
    op.create_index('uq_installation_active_per_number', 'installations', ['number_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('line_directory_entries',
    sa.Column('pattern', sa.String(length=32), nullable=False),
    sa.Column('kind', postgresql.ENUM('exact', 'prefix', 'suffix', name='directory_rule_kind', create_type=False), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_line_directory_entries_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_directory_entries')),
    sa.UniqueConstraint('pattern', 'kind', name='uq_line_directory_entries_pattern_kind')
    )
    op.create_table('number_assignments',
    sa.Column('number_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_number_assignments_valid_period')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_number_assignments_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_number_assignments_closed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_number_assignments_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['number_id'], ['registered_numbers.id'], name=op.f('fk_number_assignments_number_id_registered_numbers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_assignments'))
    )
    op.create_index('ix_assignments_agent_range', 'number_assignments', ['agent_id', sa.text('valid_from DESC')], unique=False)
    op.create_index('ix_assignments_number_range', 'number_assignments', ['number_id', sa.text('valid_from DESC')], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_live', 'refresh_tokens', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('ix_refresh_tokens_user', 'refresh_tokens', ['user_id', 'issued_at'], unique=False)
    op.create_table('service_tokens',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_service_tokens_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_tokens')),
    sa.UniqueConstraint('name', name=op.f('uq_service_tokens_name')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_service_tokens_token_hash'))
    )
    op.create_table('alerts',
    sa.Column('kind', postgresql.ENUM('capture_disabled', 'permission_lost_microphone', 'permission_lost_phone_state', 'permission_lost_call_log', 'battery_optimisation_reenabled', 'app_force_stopped', 'install_disappeared', 'recording_route_lost', 'service_not_running', 'device_offline', 'device_silent', 'fleet_silent', 'capture_rate_regression', 'queue_full', 'storage_low', 'poisoned_record', 'auth_expired', 'credential_replay', 'installation_rebound', 'callback_receiver_down', 'enrolment_stalled', 'attribution_out_of_range', 'attribution_discarded_spike', 'retention_job_failed', 'backup_failed', 'storage_capacity_low', 'min_version_refusals', name='alert_kind', create_type=False), nullable=False),
    sa.Column('severity', postgresql.ENUM('info', 'warning', 'critical', name='alert_severity', create_type=False), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('installation_id', sa.UUID(), nullable=True),
    sa.Column('number_id', sa.UUID(), nullable=True),
    sa.Column('device_model', sa.String(length=96), nullable=True),
    sa.Column('title_uz', sa.String(length=200), nullable=False),
    sa.Column('body_uz', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_alerts_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_alerts_installation_id_installations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['number_id'], ['registered_numbers.id'], name=op.f('fk_alerts_number_id_registered_numbers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_feed', 'alerts', ['severity', sa.text('last_seen_at DESC')], unique=False)
    op.create_index('uq_alerts_open', 'alerts', ['dedupe_key'], unique=True, postgresql_where=sa.text('acknowledged_at IS NULL AND resolved_at IS NULL'))
    op.create_table('audit_log',
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', postgresql.ENUM('user', 'service', 'device', 'system', name='actor_type', create_type=False), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_service_token_id', sa.UUID(), nullable=True),
    sa.Column('action', postgresql.ENUM('login_succeeded', 'login_failed', 'logout', 'password_changed', 'password_reset', 'user_created', 'user_updated', 'user_deactivated', 'agent_created', 'agent_updated', 'agent_archived', 'agents_imported', 'number_created', 'number_updated', 'assignment_created', 'assignment_closed', 'calls_reattributed', 'enrolment_code_issued', 'enrolment_code_revoked', 'installation_attested', 'installation_revoked', 'installation_rebound', 'call_note_updated', 'calls_exported', 'audio_play', 'audio_download', 'audio_deleted', 'alert_acknowledged', 'setting_updated', 'line_directory_updated', 'supported_model_updated', 'app_version_published', 'service_token_created', 'service_token_revoked', 'export_read', name='audit_action', create_type=False), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_service_token_id'], ['service_tokens.id'], name=op.f('fk_audit_log_actor_service_token_id_service_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_actor', 'audit_log', ['actor_user_id', sa.text('at DESC')], unique=False)
    op.create_index('ix_audit_log_at', 'audit_log', [sa.text('at DESC')], unique=False)
    op.create_index('ix_audit_log_object', 'audit_log', ['object_type', 'object_id', sa.text('at DESC')], unique=False)
    op.create_table('call_log_deltas',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('number_id', sa.UUID(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('device_counted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('uploaded_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('subscription_unknown_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('delta', sa.Integer(), sa.Computed('device_counted - uploaded_count', persisted=True), nullable=False),
    sa.Column('first_reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_call_log_deltas_installation_id_installations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['number_id'], ['registered_numbers.id'], name=op.f('fk_call_log_deltas_number_id_registered_numbers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_log_deltas')),
    sa.UniqueConstraint('installation_id', 'period_date', name='uq_call_log_deltas_installation_period')
    )
    op.create_index('ix_call_log_deltas_open', 'call_log_deltas', ['period_date', 'delta'], unique=False, postgresql_where=sa.text('closed_at IS NULL'))
    op.create_table('calls',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('client_call_id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('number_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('direction', postgresql.ENUM('incoming', 'outgoing', name='call_direction', create_type=False), nullable=False),
    sa.Column('disposition', postgresql.ENUM('answered', 'missed', 'rejected', 'no_answer', name='call_disposition', create_type=False), nullable=False),
    sa.Column('remote_number', sa.String(length=32), nullable=True),
    sa.Column('remote_number_key', sa.CHAR(length=9), sa.Computed("CASE WHEN (length(regexp_replace(remote_number, '[^0-9]', '', 'g')) >= 9) THEN right(regexp_replace(remote_number, '[^0-9]', '', 'g'), 9) END", persisted=True), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('call_type', postgresql.ENUM('internal', 'external', 'unknown', name='call_type', create_type=False), server_default='unknown', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ring_sec', sa.Integer(), nullable=True),
    sa.Column('device_epoch_ms', sa.BigInteger(), nullable=False),
    sa.Column('device_timezone', sa.String(length=64), nullable=False),
    sa.Column('clock_skew_sec', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sim_subscription_id', sa.Integer(), nullable=True),
    sa.Column('sim_slot', sa.SmallInteger(), nullable=True),
    sa.Column('source', postgresql.ENUM('live_capture', 'call_log_recovery', name='call_source', create_type=False), nullable=False),
    sa.Column('reconciled_with_call_log', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=True),
    sa.Column('has_audio', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('audio_missing_reason', postgresql.ENUM('pending_upload', 'not_expected', 'recording_route_unavailable', 'oem_recorder_off', 'no_permission', 'capture_returned_silence', 'app_not_running', 'upload_expired', 'queue_space_exhausted', 'attribution_failed', name='audio_missing_reason', create_type=False), nullable=True),
    sa.Column('audio_duration_mismatch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=False),
    sa.Column('app_variant', postgresql.ENUM('legacy28', 'modern34', name='app_variant', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(direction = 'incoming' AND disposition IN ('answered','missed','rejected')) OR (direction = 'outgoing' AND disposition IN ('answered','no_answer'))", name=op.f('ck_calls_direction_disposition')),
    sa.CheckConstraint("(disposition = 'answered' AND duration_sec > 0) OR (disposition <> 'answered' AND duration_sec = 0)", name=op.f('ck_calls_answered_has_duration')),
    sa.CheckConstraint("(disposition = 'answered') = (answered_at IS NOT NULL)", name=op.f('ck_calls_answered_has_timestamp')),
    sa.CheckConstraint('(has_audio AND audio_missing_reason IS NULL) OR (NOT has_audio AND audio_missing_reason IS NOT NULL)', name=op.f('ck_calls_audio_reason_present')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_calls_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assignment_id'], ['number_assignments.id'], name=op.f('fk_calls_assignment_id_number_assignments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_calls_installation_id_installations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['number_id'], ['registered_numbers.id'], name=op.f('fk_calls_number_id_registered_numbers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls')),
    sa.UniqueConstraint('client_call_id', name=op.f('uq_calls_client_call_id')),
    sa.UniqueConstraint('seq', name=op.f('uq_calls_seq'))
    )
    op.create_index('ix_calls_agent', 'calls', ['agent_id', sa.text('started_at DESC')], unique=False)
    op.create_index('ix_calls_cursor', 'calls', [sa.text('received_at DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_calls_install', 'calls', ['installation_id', sa.text('started_at DESC')], unique=False)
    op.create_index('ix_calls_no_audio', 'calls', [sa.text('started_at DESC')], unique=False, postgresql_where=sa.text('has_audio = false'))
    op.create_index('ix_calls_number', 'calls', ['number_id', sa.text('started_at DESC')], unique=False)
    op.create_index('ix_calls_remote', 'calls', ['remote_number_key'], unique=False, postgresql_where=sa.text('remote_number_key IS NOT NULL'))
    op.create_index('ix_calls_started', 'calls', [sa.text('started_at DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_calls_type', 'calls', ['call_type', sa.text('started_at DESC')], unique=False)
    op.create_index('uq_calls_command', 'calls', ['command_id'], unique=True, postgresql_where=sa.text('command_id IS NOT NULL'))
    op.create_table('capability_states',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('capability', postgresql.ENUM('phone_state', 'call_log', 'microphone', 'contacts', 'notifications', 'call_phone', 'battery_exemption', 'storage_access', 'oem_autostart', 'foreground_service', 'oem_recorder', 'subscription_resolution', name='capability', create_type=False), nullable=False),
    sa.Column('state', postgresql.ENUM('granted_working', 'granted_not_working', 'denied', 'denied_permanently', 'not_applicable', 'unknown', name='capability_state', create_type=False), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_capability_states_installation_id_installations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_states')),
    sa.UniqueConstraint('installation_id', 'capability', name='uq_capability_states_installation_capability')
    )
    op.create_table('capability_transitions',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('capability', postgresql.ENUM('phone_state', 'call_log', 'microphone', 'contacts', 'notifications', 'call_phone', 'battery_exemption', 'storage_access', 'oem_autostart', 'foreground_service', 'oem_recorder', 'subscription_resolution', name='capability', create_type=False), nullable=False),
    sa.Column('from_state', postgresql.ENUM('granted_working', 'granted_not_working', 'denied', 'denied_permanently', 'not_applicable', 'unknown', name='capability_state', create_type=False), nullable=True),
    sa.Column('to_state', postgresql.ENUM('granted_working', 'granted_not_working', 'denied', 'denied_permanently', 'not_applicable', 'unknown', name='capability_state', create_type=False), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('device_report', 'admin_recheck', 'inferred')", name=op.f('ck_capability_transitions_source_known')),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_capability_transitions_installation_id_installations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_transitions'))
    )
    op.create_index('ix_capability_transitions_capability', 'capability_transitions', ['capability', sa.text('at DESC')], unique=False)
    op.create_index('ix_capability_transitions_installation', 'capability_transitions', ['installation_id', sa.text('at DESC')], unique=False)
    op.create_table('data_usage_daily',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('cellular_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('wifi_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('requests', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_data_usage_daily_installation_id_installations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_usage_daily')),
    sa.UniqueConstraint('installation_id', 'period_date', name='uq_data_usage_daily_installation_period')
    )
    op.create_table('device_health',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_call_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('app_variant', postgresql.ENUM('legacy28', 'modern34', name='app_variant', create_type=False), nullable=True),
    sa.Column('api_level', sa.Integer(), nullable=True),
    sa.Column('battery_level', sa.SmallInteger(), nullable=True),
    sa.Column('battery_charging', sa.Boolean(), nullable=True),
    sa.Column('battery_optimisation_exempt', sa.Boolean(), nullable=True),
    sa.Column('power_save_mode', sa.Boolean(), nullable=True),
    sa.Column('free_storage_bytes', sa.BigInteger(), nullable=True),
    sa.Column('queue_records', sa.Integer(), nullable=True),
    sa.Column('queue_bytes', sa.BigInteger(), nullable=True),
    sa.Column('queue_oldest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parked_records', sa.Integer(), nullable=True),
    sa.Column('clock_skew_sec', sa.Integer(), nullable=True),
    sa.Column('device_timezone', sa.String(length=64), nullable=True),
    sa.Column('network_type', postgresql.ENUM('wifi', 'cellular', 'none', name='network_type', create_type=False), nullable=True),
    sa.Column('cellular_bytes_month', sa.BigInteger(), nullable=True),
    sa.Column('service_running', sa.Boolean(), nullable=True),
    sa.Column('capture_enabled', sa.Boolean(), nullable=True),
    sa.Column('recording_route', postgresql.ENUM('oem_file_harvest', 'app_voice_recognition', 'app_voice_communication', 'app_mic', 'none', name='capture_route', create_type=False), nullable=True),
    sa.Column('recording_route_ok', sa.Boolean(), nullable=True),
    sa.Column('ws_connected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_device_health_installation_id_installations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('installation_id', name=op.f('pk_device_health'))
    )
    op.create_table('enrolment_attempts',
    sa.Column('kind', postgresql.ENUM('code_redeem', 'msisdn_check', 'callback_start', 'callback_match', 'admin_attest', 'step_timing', name='enrolment_attempt_kind', create_type=False), nullable=False),
    sa.Column('outcome', postgresql.ENUM('ok', 'code_not_found', 'code_already_used', 'code_expired', 'code_revoked', 'number_mismatch', 'msisdn_empty', 'no_caller_id', 'timeout', 'receiver_down', 'already_bound', 'rejected', name='enrolment_outcome', create_type=False), nullable=False),
    sa.Column('code_id', sa.UUID(), nullable=True),
    sa.Column('number_id', sa.UUID(), nullable=True),
    sa.Column('installation_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('step', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remote_ip', postgresql.INET(), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('device_model', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_enrolment_attempts_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['code_id'], ['enrolment_codes.id'], name=op.f('fk_enrolment_attempts_code_id_enrolment_codes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_enrolment_attempts_installation_id_installations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['number_id'], ['registered_numbers.id'], name=op.f('fk_enrolment_attempts_number_id_registered_numbers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrolment_attempts'))
    )
    op.create_index('ix_enrolment_attempts_installation', 'enrolment_attempts', ['installation_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_enrolment_attempts_kind', 'enrolment_attempts', ['kind', 'outcome', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_enrolment_attempts_number', 'enrolment_attempts', ['number_id', sa.text('created_at DESC')], unique=False)
    op.create_table('number_verifications',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('number_id', sa.UUID(), nullable=False),
    sa.Column('method', postgresql.ENUM('sim_msisdn', 'callback', 'admin_attested', name='verification_method', create_type=False), nullable=False),
    sa.Column('state', postgresql.ENUM('pending', 'matched', 'failed', 'expired', 'attested', name='verification_state', create_type=False), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matched_event_id', sa.UUID(), nullable=True),
    sa.Column('failure_outcome', postgresql.ENUM('ok', 'code_not_found', 'code_already_used', 'code_expired', 'code_revoked', 'number_mismatch', 'msisdn_empty', 'no_caller_id', 'timeout', 'receiver_down', 'already_bound', 'rejected', name='enrolment_outcome', create_type=False), nullable=True),
    sa.Column('attested_by', sa.UUID(), nullable=True),
    sa.Column('attest_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attested_by'], ['users.id'], name=op.f('fk_number_verifications_attested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_number_verifications_installation_id_installations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['number_id'], ['registered_numbers.id'], name=op.f('fk_number_verifications_number_id_registered_numbers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_verifications'))
    )
    op.create_index('ix_number_verifications_installation', 'number_verifications', ['installation_id', sa.text('started_at DESC')], unique=False)
    op.create_index('ix_number_verifications_pending', 'number_verifications', ['number_id'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    op.create_table('audio_upload_sessions',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('client_call_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('bytes_total', sa.BigInteger(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('received_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('sha256_expected', sa.CHAR(length=64), nullable=False),
    sa.Column('codec', postgresql.ENUM('opus', 'aac_lc', name='audio_codec', create_type=False), nullable=False),
    sa.Column('container', postgresql.ENUM('ogg', 'mp4', name='audio_container', create_type=False), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('capture_route', postgresql.ENUM('oem_file_harvest', 'app_voice_recognition', 'app_voice_communication', 'app_mic', 'none', name='capture_route', create_type=False), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('part_path', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'committed', 'expired', 'aborted', name='upload_status', create_type=False), server_default='open', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_chunk_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_audio_upload_sessions_call_id_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_audio_upload_sessions_installation_id_installations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_upload_sessions'))
    )
    op.create_index('ix_audio_sessions_sweep', 'audio_upload_sessions', ['status', 'expires_at'], unique=False)
    op.create_index('uq_audio_sessions_open', 'audio_upload_sessions', ['installation_id', 'client_call_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('call_audio',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('codec', postgresql.ENUM('opus', 'aac_lc', name='audio_codec', create_type=False), nullable=False),
    sa.Column('container', postgresql.ENUM('ogg', 'mp4', name='audio_container', create_type=False), nullable=False),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('channels', sa.SmallInteger(), nullable=True),
    sa.Column('bitrate_bps', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('capture_route', postgresql.ENUM('oem_file_harvest', 'app_voice_recognition', 'app_voice_communication', 'app_mic', 'none', name='capture_route', create_type=False), nullable=False),
    sa.Column('capture_route_detail', sa.String(length=64), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("deleted_reason IS NULL OR deleted_reason IN ('retention', 'revocation')", name=op.f('ck_call_audio_deleted_reason_known')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_audio_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_audio')),
    sa.UniqueConstraint('call_id', name=op.f('uq_call_audio_call_id'))
    )
    op.create_index('ix_call_audio_live', 'call_audio', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_call_audio_route', 'call_audio', ['capture_route'], unique=False)
    op.create_table('commands',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('kind', postgresql.ENUM('dial', 'config', 'logout', 'ping', 'recheck', name='command_kind', create_type=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'sent', 'acknowledged', 'failed', 'expired', name='command_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('failure_reason', postgresql.ENUM('device_offline', 'no_permission', 'os_refused', 'ack_timeout', 'discarded_stale', 'unsupported', 'busy', name='command_failure_reason', create_type=False), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_call_id', sa.UUID(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_commands_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_commands_installation_id_installations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_call_id'], ['calls.id'], name=op.f('fk_commands_result_call_id_calls'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commands'))
    )
    op.create_index('ix_commands_expiry', 'commands', ['status', 'expires_at'], unique=False)
    op.create_index('ix_commands_installation', 'commands', ['installation_id', 'status', sa.text('created_at DESC')], unique=False)

    _create_deferred_foreign_keys()
    _create_assignment_exclusion()
    _create_audit_immutability_trigger()
    op.bulk_insert(
        _settings_table,
        [
            {"key": key, "value": value, "value_type": value_type}
            for key, value, value_type in SETTINGS_SEED
        ],
    )


def downgrade() -> None:
    op.execute(sa.text("DROP TRIGGER IF EXISTS audit_log_no_change ON audit_log"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS audit_log_immutable()"))
    for name, table, _referred, _column in DEFERRED_FOREIGN_KEYS:
        op.drop_constraint(name, table, type_="foreignkey")

    op.drop_index('ix_commands_installation', table_name='commands')
    op.drop_index('ix_commands_expiry', table_name='commands')
    op.drop_table('commands')
    op.drop_index('ix_call_audio_route', table_name='call_audio')
    op.drop_index('ix_call_audio_live', table_name='call_audio', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('call_audio')
    op.drop_index('uq_audio_sessions_open', table_name='audio_upload_sessions', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_audio_sessions_sweep', table_name='audio_upload_sessions')
    op.drop_table('audio_upload_sessions')
    op.drop_index('ix_number_verifications_pending', table_name='number_verifications', postgresql_where=sa.text("state = 'pending'"))
    op.drop_index('ix_number_verifications_installation', table_name='number_verifications')
    op.drop_table('number_verifications')
    op.drop_index('ix_enrolment_attempts_number', table_name='enrolment_attempts')
    op.drop_index('ix_enrolment_attempts_kind', table_name='enrolment_attempts')
    op.drop_index('ix_enrolment_attempts_installation', table_name='enrolment_attempts')
    op.drop_table('enrolment_attempts')
    op.drop_table('device_health')
    op.drop_table('data_usage_daily')
    op.drop_index('ix_capability_transitions_installation', table_name='capability_transitions')
    op.drop_index('ix_capability_transitions_capability', table_name='capability_transitions')
    op.drop_table('capability_transitions')
    op.drop_table('capability_states')
    op.drop_index('uq_calls_command', table_name='calls', postgresql_where=sa.text('command_id IS NOT NULL'))
    op.drop_index('ix_calls_type', table_name='calls')
    op.drop_index('ix_calls_started', table_name='calls')
    op.drop_index('ix_calls_remote', table_name='calls', postgresql_where=sa.text('remote_number_key IS NOT NULL'))
    op.drop_index('ix_calls_number', table_name='calls')
    op.drop_index('ix_calls_no_audio', table_name='calls', postgresql_where=sa.text('has_audio = false'))
    op.drop_index('ix_calls_install', table_name='calls')
    op.drop_index('ix_calls_cursor', table_name='calls')
    op.drop_index('ix_calls_agent', table_name='calls')
    op.drop_table('calls')
    op.drop_index('ix_call_log_deltas_open', table_name='call_log_deltas', postgresql_where=sa.text('closed_at IS NULL'))
    op.drop_table('call_log_deltas')
    op.drop_index('ix_audit_log_object', table_name='audit_log')
    op.drop_index('ix_audit_log_at', table_name='audit_log')
    op.drop_index('ix_audit_log_actor', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_alerts_open', table_name='alerts', postgresql_where=sa.text('acknowledged_at IS NULL AND resolved_at IS NULL'))
    op.drop_index('ix_alerts_feed', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('service_tokens')
    op.drop_index('ix_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_live', table_name='refresh_tokens', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('refresh_tokens')
    op.drop_index('ix_assignments_number_range', table_name='number_assignments')
    op.drop_index('ix_assignments_agent_range', table_name='number_assignments')
    op.drop_table('number_assignments')
    op.drop_table('line_directory_entries')
    op.drop_index('uq_installation_active_per_number', table_name='installations', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_installations_stage', table_name='installations')
    op.drop_index('ix_installations_agent', table_name='installations')
    op.drop_table('installations')
    op.drop_index('ix_codes_number_active', table_name='enrolment_codes', postgresql_where=sa.text('redeemed_at IS NULL AND revoked_at IS NULL'))
    op.drop_table('enrolment_codes')
    op.drop_index('uq_app_versions_current', table_name='app_versions', postgresql_where=sa.text('is_current'))
    op.drop_table('app_versions')
    op.drop_table('app_settings')
    op.drop_index('ix_users_agent_id', table_name='users')
    op.drop_index('ix_users_active_admin', table_name='users', postgresql_where=sa.text("is_active AND role = 'admin'"))
    op.drop_table('users')
    op.drop_index('ix_callback_events_receiver', table_name='callback_events')
    op.drop_index('ix_callback_events_caller', table_name='callback_events')
    op.drop_table('callback_events')
    op.drop_table('supported_models')
    op.drop_table('storage_usage_daily')
    op.drop_index('ix_registered_numbers_active', table_name='registered_numbers')
    op.drop_table('registered_numbers')
    op.drop_table('model_capture_stats')
    op.drop_index('ix_devices_model', table_name='devices')
    op.drop_table('devices')
    op.drop_table('callback_receivers')
    op.drop_index('uq_agents_employee_code', table_name='agents', postgresql_where=sa.text('employee_code IS NOT NULL'))
    op.drop_index(op.f('ix_agents_full_name'), table_name='agents')
    op.drop_index('ix_agents_active', table_name='agents')
    op.drop_table('agents')

    for type_name in PG_ENUMS:
        _enum(type_name).drop(op.get_bind(), checkfirst=False)
    # Extensions are left in place: another schema in the same database may be
    # using them, and dropping one is not this revision's to undo.


def _create_extensions() -> None:
    """Create the extensions the schema needs, before anything uses them.

    Written out as literal statements rather than built from :data:`EXTENSIONS`
    because SQL is never assembled by interpolation in this project
    (CONVENTIONS.md §15). A test asserts the two lists agree.
    """
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS "btree_gist"'))
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS "citext"'))


def _create_deferred_foreign_keys() -> None:
    for name, table, referred, column in DEFERRED_FOREIGN_KEYS:
        op.create_foreign_key(name, table, referred, [column], ["id"], ondelete="SET NULL")


def _create_assignment_exclusion() -> None:
    """Exactly one agent holds a number at any instant (UC-07, R18).

    An application-level check loses to two admins clicking at once. This
    cannot, and it is the whole reason ``btree_gist`` is installed: the ``=``
    operator on a UUID is not available to a GiST index without it, and without
    the extension this statement does not silently degrade — it fails, which is
    why it is a separate, readable statement rather than a line in a table
    definition somebody could delete.
    """
    op.execute(
        sa.text(
            "ALTER TABLE number_assignments "
            "ADD CONSTRAINT number_assignment_no_overlap "
            "EXCLUDE USING gist ("
            "  number_id WITH =,"
            "  tstzrange(valid_from, valid_to, '[)') WITH &&"
            ")"
        )
    )


def _create_audit_immutability_trigger() -> None:
    """``audit_log`` is append-only, enforced by the database (UC-24, N27)."""
    op.execute(
        sa.text(
            "CREATE FUNCTION audit_log_immutable() RETURNS trigger AS $$ "
            "BEGIN RAISE EXCEPTION 'audit_log is append-only'; END $$ LANGUAGE plpgsql"
        )
    )
    op.execute(
        sa.text(
            "CREATE TRIGGER audit_log_no_change "
            "BEFORE UPDATE OR DELETE ON audit_log "
            "FOR EACH ROW EXECUTE FUNCTION audit_log_immutable()"
        )
    )
